import test from "node:test";
import assert from "node:assert/strict";
import { readFile, access } from "node:fs/promises";
const root=new URL("..",import.meta.url);
test("Pix exposes only its focused capability set",async()=>{const j=JSON.parse(await readFile(new URL("package.json",root)));const e=j.pi.extensions.join("\n");for(const x of ["./extensions/upstream-tools.ts","./extensions/capabilities.ts"]) assert.ok(e.includes(x));assert.equal(j["pi-subagents"],undefined);assert.equal(j.pi.skills,undefined);});
test("prompt snapshots and comparison exist",async()=>{for(const p of ["docs/prompts/pi-default.txt","docs/prompts/pix-default.txt","docs/system-prompts.html"])await access(new URL(p,root));});

test("slash commands stay minimal", async () => {
  const capabilities = await readFile(new URL("extensions/capabilities.ts", root), "utf8");
  const fast = await readFile(new URL("extensions/fast-mode.ts", root), "utf8");
  const upstream = await readFile(new URL("extensions/upstream-tools.ts", root), "utf8");
  const todo = await readFile(new URL("extensions/todo.ts", root), "utf8");
  const bench = await readFile(new URL("extensions/benchmark.ts", root), "utf8");
  const prompt = await readFile(new URL("extensions/prompt-inspector.ts", root), "utf8");
  const smartEditor = await readFile(new URL("extensions/smart-editor.ts", root), "utf8");
  for (const dependency of ["pi-subagents", "pi-web-access", "@narumitw/pi-lsp"]) assert.match(upstream, new RegExp(dependency));
  assert.match(upstream, /property === "registerCommand"/);
  assert.match(upstream, /PI_SUBAGENT_MAX_DEPTH/);
  assert.match(upstream, /Math\.min\(requestedConcurrency, 4\)/);
  assert.match(upstream, /Math\.min\(requestedSpawns, 8\)/);
  assert.match(capabilities, /websearch/);
  assert.match(capabilities, /subagent/);
  assert.match(fast, /registerCommand\("fast"/);
  assert.match(fast, /Usage: \/fast \[on\|off\|status\]/);
  assert.match(fast, /getArgumentCompletions/);
  assert.match(capabilities, /action !== "on" && action !== "off"/);
  assert.match(capabilities, /action === "config"/);
  assert.match(capabilities, /getArgumentCompletions/);
  assert.match(capabilities, /ctx\.scopedModels\.length/);
  assert.match(capabilities, /ctx\.scopedModels\.map/);
  assert.match(capabilities, /const agents = \["worker", "scout"\]/);
  assert.doesNotMatch(capabilities, /critic/);
  assert.match(todo, /registerCommand\("todo"/);
  assert.doesNotMatch(todo, /registerCommand\("todos"/);
  assert.match(todo, /Usage: \/todo \[on\|off\]/);
  assert.match(todo, /parentId/);
  assert.match(todo, /theme\.fg\("accent"/);
  assert.match(todo, /prepareArguments/);
  assert.match(todo, /getArgumentCompletions/);
  assert.match(bench, /registerCommand\("bench"/);
  assert.doesNotMatch(bench, /bench speed|bench doctor/);
  assert.match(prompt, /registerCommand\("prompt"/);
  assert.doesNotMatch(prompt, /registerCommand\("pix-prompt"/);
  const historyCompletion = await readFile(new URL("extensions/history-completion.ts", root), "utf8");
  assert.match(historyCompletion, /historySuggestion/);
  assert.doesNotMatch(historyCompletion, /addAutocompleteProvider/);
  assert.match(smartEditor, /registerHistoryCompletion\(pi\)/);
  assert.match(smartEditor, /CURSOR_MARKER/);
  assert.match(smartEditor, /editorTheme\.selectList\.description/);
  assert.doesNotMatch(smartEditor, /uiTheme\.fg/);
  assert.match(smartEditor, /super\(tui, editorTheme, keybindings\)/);
  await access(new URL("extensions/question.ts", root));
});
