/**
 * A Chrome shim that suppresses the "Keychain Not Found" dialog.
 *
 * The managed browser runs with a throwaway `--user-data-dir`. On first start
 * Chrome wants a key from the login keychain to encrypt saved passwords, the
 * fresh profile has no entitlement to the existing "Chrome Safe Storage" item,
 * and macOS puts a modal in front of whatever the user is doing. The profile is
 * discarded when the session ends, so nothing in it is worth encrypting.
 *
 * `--use-mock-keychain` makes Chrome use an in-memory store instead. The
 * backend builds its own argument list with no hook for extra flags, but it
 * honours PI_COMPUTER_USE_CHROME_EXECUTABLE, so a wrapper script that appends
 * the flag and execs the real binary is the supported way in.
 */

import { chmodSync, mkdirSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

/** Flags added to every managed-browser launch. */
export const SUPPRESSION_FLAGS = [
	// Do not reach for the login keychain for a profile that is about to be deleted.
	"--use-mock-keychain",
	// A throwaway profile is never the default browser and has no first run to complete.
	"--no-first-run",
	"--no-default-browser-check",
	// Nothing here should sync to or prompt about an account.
	"--disable-sync",
];

export const wrapperScript = (executable: string): string =>
	[
		"#!/bin/sh",
		"# Generated by pix. Launches Chrome for computer use without the macOS",
		"# keychain prompt a throwaway profile would otherwise trigger.",
		`exec ${JSON.stringify(executable)} ${SUPPRESSION_FLAGS.join(" ")} "$@"`,
		"",
	].join("\n");

export interface WrapperOptions {
	/** Real browser binary to delegate to. */
	executable: string;
	/** Directory for the shim; defaults to a pix directory under the system temp dir. */
	directory?: string;
}

/**
 * Write the shim and return its path.
 *
 * Rewritten on every call so a Chrome upgrade or a changed flag list cannot
 * leave a stale script behind.
 */
export const installWrapper = ({ executable, directory }: WrapperOptions): string => {
	const dir = directory ?? join(tmpdir(), "pix-chrome");
	mkdirSync(dir, { recursive: true });
	const script = join(dir, "chrome-for-computer-use");
	writeFileSync(script, wrapperScript(executable), "utf8");
	chmodSync(script, 0o755);
	return script;
};

/** Where the real Chrome lives, in the same order the backend searches. */
export const CHROME_CANDIDATES = [
	"/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
	join(process.env.HOME ?? "", "Applications/Google Chrome.app/Contents/MacOS/Google Chrome"),
];
