// Static mobile web app served by the remote-control hub. Kept dependency-free so the hub has no build step.

export const remoteIconSvg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 180 180"><rect width="180" height="180" rx="40" fill="#111"/><path d="M58 122V58h38c17 0 28 10 28 25s-11 25-28 25H76v14z" fill="none" stroke="#fff" stroke-width="12" stroke-linejoin="round"/></svg>`;

export const remoteManifest = JSON.stringify({
  name: "Pix Remote",
  short_name: "Pix",
  display: "standalone",
  background_color: "#f5f5f7",
  theme_color: "#f5f5f7",
  start_url: "/",
  icons: [{ src: "/icon.svg", sizes: "any", type: "image/svg+xml", purpose: "any" }],
});

export const remoteAppHtml = String.raw`<!doctype html>
<html lang="en"><head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover,interactive-widget=resizes-content">
<meta name="apple-mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-status-bar-style" content="default">
<meta name="apple-mobile-web-app-title" content="Pix"><meta name="theme-color" content="#f5f5f7">
<link rel="manifest" href="/manifest.webmanifest"><link rel="apple-touch-icon" href="/icon.svg">
<title>Pix Remote</title>
<style>
:root{color-scheme:light dark;--bg:#fff;--panel:rgba(255,255,255,.94);--card:#f7f7f8;--text:#202124;--muted:#777981;--line:rgba(0,0,0,.075);--accent:#26282c;--me:#f1f2f4;--me-text:#202124;--code:#f3f4f5}
@media(prefers-color-scheme:dark){:root{--bg:#17181a;--panel:rgba(23,24,26,.94);--card:#252629;--text:#f3f3f4;--muted:#a0a1a6;--line:rgba(255,255,255,.09);--accent:#ececef;--me:#303136;--me-text:#f3f3f4;--code:#202125}}
[hidden]{display:none!important}*{box-sizing:border-box;-webkit-tap-highlight-color:transparent}html,body{height:100%;margin:0}
body{font:16px/1.45 -apple-system,BlinkMacSystemFont,"SF Pro Text",system-ui,sans-serif;background:var(--bg);color:var(--text);overflow:hidden;-webkit-font-smoothing:antialiased}
button,textarea,input{font:inherit;color:inherit}button{border:0;background:none;cursor:pointer}
.app{position:fixed;inset:0 0 var(--keyboard-offset,0px);display:flex}
.list{width:min(340px,86vw);height:100%;background:var(--panel);backdrop-filter:saturate(180%) blur(24px);-webkit-backdrop-filter:saturate(180%) blur(24px);border-right:1px solid var(--line);padding:calc(env(safe-area-inset-top) + 14px) 12px 12px;overflow:auto;transition:transform .32s cubic-bezier(.2,.8,.2,1);z-index:3}
.list h1{font-size:28px;letter-spacing:-.02em;margin:8px 8px 14px}.row{width:100%;text-align:left;padding:12px;border-radius:14px;display:block}.row.on{background:var(--card);box-shadow:0 1px 2px rgba(0,0,0,.06)}
.row b{display:flex;align-items:center;gap:8px;font-weight:600;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.pair-link{margin:18px 12px;color:var(--muted);font-size:14px;min-height:44px}.group h2{font-size:13px;font-weight:600;color:var(--muted);margin:14px 12px 4px}.group:first-child h2{margin-top:0}.row small{display:block;color:var(--muted);white-space:nowrap;overflow:hidden;text-overflow:ellipsis;margin-top:2px}
.row-wrap{display:flex;align-items:center}.row-wrap .row{flex:1;min-width:0}.row-more{width:40px;height:44px;flex:none;color:var(--muted);border-radius:12px;font-size:18px}.new-session{margin:4px 0 6px;color:var(--text);font-weight:600;min-height:44px}.memory-row{padding:9px 12px}.sheet-list{max-height:52vh;overflow:auto}.memory-view{position:fixed;inset:0;z-index:12;background:var(--bg);display:flex;flex-direction:column}.memory-view header{height:auto;min-height:calc(env(safe-area-inset-top) + 54px)}.memory-view .chat{padding-bottom:calc(env(safe-area-inset-bottom) + 24px)}
.dot{width:7px;height:7px;border-radius:50%;background:#34c759;flex:none}.dot.busy{background:#ff9f0a;animation:pulse 1.2s infinite}.ask{margin:10px 0;padding:12px;border-radius:14px;background:rgba(10,132,255,.12);border:1px solid rgba(10,132,255,.35)}.ask p{margin:0 0 10px;white-space:pre-wrap}.ask button{display:block;width:100%;text-align:left;margin:6px 0;padding:10px 12px;border-radius:10px;border:1px solid rgba(127,127,127,.35);background:transparent;color:inherit;font:inherit}.ask button small{display:block;opacity:.65}.ask .hint{font-size:12px;opacity:.65;margin:6px 0 0}.dot.wait{background:#0a84ff;animation:pulse 2.4s infinite}@keyframes pulse{50%{opacity:.35}}
.main{flex:1;min-width:0;display:flex;flex-direction:column;height:100%}
header{height:calc(env(safe-area-inset-top) + 54px);padding:env(safe-area-inset-top) 16px 0;display:flex;align-items:center;gap:10px;background:var(--panel);border-bottom:1px solid var(--line);z-index:2}
header .title{flex:1;min-width:0;display:flex;align-items:center;gap:8px}header .title b{display:block;font-size:15px;font-weight:600;letter-spacing:-.01em;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}header .title small{display:none}
.icon{width:44px;height:44px;border-radius:12px;display:grid;place-items:center;color:var(--text);font-size:19px;flex:none}.icon:active{background:var(--card)}
.connection{width:7px;height:7px;border-radius:50%;background:#e0a64c;opacity:0;flex:none}.connection.offline{opacity:1}header .connection{margin-right:13px}
.chat{flex:1;overflow:auto;padding:24px 20px 14px;-webkit-overflow-scrolling:touch;overscroll-behavior:contain;overflow-anchor:none}
.main{position:relative}
.to-bottom{position:absolute;right:16px;bottom:calc(88px + env(safe-area-inset-bottom));z-index:5;width:40px;height:40px;border-radius:50%;background:var(--bg);color:var(--text);border:1px solid var(--line);box-shadow:0 4px 16px rgba(0,0,0,.14);font-size:19px}.inner{max-width:720px;margin:auto}
.msg{margin:0 0 22px;display:flex}.msg.user{justify-content:flex-end}.bubble{max-width:90%;white-space:pre-wrap;overflow-wrap:anywhere;min-width:0}
.user .bubble{background:var(--me);color:var(--me-text);padding:10px 15px;border-radius:17px}.assistant .bubble{padding:2px 0;line-height:1.6;max-width:100%}.system .bubble{margin:auto;color:var(--muted);font-size:13px}
.rich{white-space:normal}.rich p{margin:0 0 .8em}.user .rich p{white-space:pre-wrap}.rich p:last-child,.rich>:last-child{margin-bottom:0}.rich h1,.rich h2,.rich h3,.rich h4{font-size:1.12em;line-height:1.3;letter-spacing:-.015em;margin:1.1em 0 .4em;font-weight:650}.rich>:first-child{margin-top:0}.rich ul,.rich ol{padding-left:1.35em;margin:.3em 0 .85em}.rich li{padding-left:.15em;margin:.25em 0}.rich li>p{margin:0}.rich blockquote{margin:.75em 0;padding:.1em 0 .1em .85em;border-left:2px solid var(--line);color:var(--muted)}.rich a{color:#2376ba;text-decoration:underline;text-decoration-color:rgba(35,118,186,.3);text-underline-offset:2px}.rich .local-link{border-bottom:1px dotted var(--muted)}.rich .local-link small{font-size:.73em;margin-left:.35em;color:var(--muted);white-space:nowrap}.rich code{font: .86em/1.45 ui-monospace,SFMono-Regular,Menlo,monospace;background:var(--code);padding:.13em .3em;border-radius:4px;overflow-wrap:anywhere}.rich pre{max-height:none;max-width:100%;margin:.75em 0 1em;white-space:pre;overflow:auto;-webkit-overflow-scrolling:touch;border-radius:9px;padding:12px}.rich pre code{background:none;padding:0;overflow-wrap:normal}.rich hr{border:0;border-top:1px solid var(--line);margin:1em 0}.rich .image-reference{color:var(--muted)}
.activity{margin:0 0 14px;max-width:100%;font-size:13px;color:var(--muted)}.activity>summary{min-height:44px;display:inline-flex;align-items:center;gap:8px;cursor:pointer;list-style:none;padding:0 4px}.activity summary::-webkit-details-marker,.tool summary::-webkit-details-marker{display:none}.activity .chevron{display:inline-block;font-size:15px;transition:transform .2s}.activity[open] .chevron{transform:rotate(90deg)}.activity .count{font-weight:600;color:var(--text)}.activity .failure{color:#d8433e}.activity .activity-list{margin:0 0 0 10px;padding:0 0 0 12px;border-left:1px solid var(--line);max-width:min(620px,90vw)}
.tool{border-radius:10px;overflow:hidden;font-size:13px}.tool summary{padding:5px 8px;min-height:44px;cursor:pointer;list-style:none;display:flex;align-items:center;gap:8px;color:var(--muted)}.tool summary b{color:var(--text);font-weight:500}.tool.err summary b{color:#d8433e}.tool .label{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;min-width:0;flex:1}.tool pre{margin:0 0 8px 8px;border-radius:8px}
.background{margin:0 0 20px;border:1px solid var(--line);background:var(--card);border-radius:12px;max-width:100%;font-size:13px}.background>summary{min-height:44px;padding:9px 12px;display:flex;align-items:center;gap:8px;list-style:none;cursor:pointer}.background summary::-webkit-details-marker{display:none}.background .status{color:var(--muted)}.background.failed .status{color:#d8433e}.background .command{white-space:nowrap;overflow:hidden;text-overflow:ellipsis;min-width:0;flex:1}.background .body{padding:0 12px 12px}.background pre{border-radius:8px;max-height:220px}.background .local{color:var(--muted);font-size:12px;margin:8px 0 0;overflow-wrap:anywhere}
.table-scroll{overflow-x:auto;margin:.6em 0 .9em;-webkit-overflow-scrolling:touch}.rich table{border-collapse:collapse;font-size:14px;line-height:1.4;min-width:100%}.rich th,.rich td{border-bottom:1px solid var(--line);padding:7px 10px;text-align:left;vertical-align:top}.rich th{font-weight:600;white-space:nowrap}.rich tr:last-child td{border-bottom:0}.diagram{margin:.6em 0 .9em}.diagram pre{white-space:pre;overflow-x:auto;overflow-wrap:normal;max-height:none;border-radius:10px;font-size:11.5px;line-height:1.25}.diagram figcaption{color:var(--muted);font-size:13px;margin-bottom:4px}pre{margin:0;padding:10px 11px;background:var(--code);white-space:pre-wrap;overflow-wrap:anywhere;font:12px/1.45 ui-monospace,SFMono-Regular,Menlo,monospace;max-height:280px;overflow:auto}
.image-card{display:block;max-width:min(280px,100%);min-width:120px;min-height:80px;border:1px solid var(--line);border-radius:12px;background:var(--card);overflow:hidden;color:var(--muted);margin:8px 0;text-align:center}.image-card img{display:block;width:100%;max-height:300px;object-fit:contain}.image-card span{display:block;padding:18px}.file-chip{display:inline-flex;align-items:center;gap:.35em;max-width:100%;vertical-align:baseline;padding:.12em .55em;margin:.05em 0;border-radius:9px;background:var(--card);border:1px solid var(--line);font-size:.92em;line-height:1.35;text-align:left}.file-chip .file-name{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;min-width:0}.file-chip small{color:var(--muted);font-size:.8em;white-space:nowrap}
.files-panel{position:fixed;right:0;top:0;height:100%;width:min(360px,88vw);background:var(--panel);backdrop-filter:saturate(180%) blur(24px);-webkit-backdrop-filter:saturate(180%) blur(24px);border-left:1px solid var(--line);padding:calc(env(safe-area-inset-top) + 14px) 10px calc(env(safe-area-inset-bottom) + 12px);overflow:auto;transform:translateX(102%);transition:transform .32s cubic-bezier(.2,.8,.2,1);z-index:3}.files-open .files-panel{transform:none;box-shadow:-20px 0 40px rgba(0,0,0,.12)}.files-open .shade{opacity:1;pointer-events:auto}.dragging .files-panel{transition:none!important}
.files-panel h1{font-size:28px;letter-spacing:-.02em;margin:8px 8px 8px}.crumbs{display:flex;flex-wrap:wrap;gap:2px;align-items:center;margin:0 4px 8px;font-size:14px;color:var(--muted)}.crumbs button{padding:6px 7px;border-radius:9px;min-height:36px}.crumbs button:last-child{color:var(--text);font-weight:600}.file-row{display:flex;align-items:center;gap:10px;width:100%;text-align:left;padding:10px;border-radius:12px;min-height:44px}.file-row .file-name{flex:1;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.file-row small{color:var(--muted);font-size:13px;white-space:nowrap}
.file-view .chat{padding-top:12px}.file-body{white-space:normal}.file-body iframe,.file-body video{width:100%;border:0;border-radius:12px;background:#000}.file-body iframe{height:calc(100vh - 150px);background:#fff}.file-body audio{width:100%}.file-body pre{white-space:pre-wrap;word-break:break-word;font:13px/1.45 ui-monospace,SFMono-Regular,Menlo,monospace}.file-meta{color:var(--muted);font-size:14px;margin:0 0 12px}.file-action{padding:0 12px;min-height:36px;border-radius:10px;background:var(--card);font-size:14px;font-weight:600;flex:none}.file-link{display:inline-block;margin-top:10px;color:var(--text)}.doc table{border-collapse:collapse}.doc td,.doc th{border:1px solid var(--line);padding:4px 8px}
.image-viewer{position:fixed;inset:0;z-index:10;background:rgba(0,0,0,.94);display:flex;align-items:center;justify-content:center;padding:42px 12px env(safe-area-inset-bottom)}.image-viewer img{max-width:100%;max-height:100%;object-fit:contain}.image-viewer button{position:absolute;right:16px;top:calc(env(safe-area-inset-top) + 12px);color:white;width:44px;height:44px;font-size:25px}
.typing{color:var(--muted)}.empty{height:70%;display:grid;place-items:center;text-align:center;color:var(--muted)}
.composer{padding:10px 16px calc(env(safe-area-inset-bottom) + 12px);background:var(--panel)}
body.keyboard .composer{padding-bottom:8px}
.box{max-width:720px;margin:auto;display:flex;align-items:flex-end;gap:8px;background:var(--card);border:1px solid var(--line);border-radius:20px;padding:6px 6px 6px 8px}.attach{width:36px;height:36px;flex:none;font-size:23px;color:var(--muted);border-radius:10px}.attachment{max-width:720px;margin:0 auto 6px;padding:5px 10px;border-radius:10px;background:var(--card);font-size:13px;display:flex;align-items:center;gap:8px}.attachment span{flex:1;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.attachment button{min-width:36px;min-height:36px}.composer-status{max-width:720px;margin:0 auto 5px;color:#b64036;font-size:13px}
textarea{flex:1;border:0;outline:0;resize:none;background:transparent;max-height:140px;padding:6px 0;line-height:1.35}
.ctx-ring{flex:none;width:30px;height:30px;padding:5px;margin-left:6px;border:0;background:none;color:var(--muted)}
.ctx-ring svg{width:20px;height:20px;transform:rotate(-90deg)}
.ctx-ring circle{fill:none;stroke-width:2.6}.ctx-ring .track{stroke:var(--line)}.ctx-ring .fill{stroke:currentColor;stroke-linecap:round;transition:stroke-dasharray .4s}
.ctx-ring.warn{color:#d08a1c}.ctx-ring.full{color:#d0453a}
.av{flex:none;align-self:flex-start;width:30px;height:30px;margin:0 8px 0 0;border-radius:50%;background:#f4f7fb;display:grid;place-items:center}.av svg{width:27px;height:27px;stroke:#2f6fa8;stroke-width:4.5;stroke-linecap:round;stroke-linejoin:round;fill:none;overflow:visible}.av .ey-dot,.av .ey-hap,.av .blush{display:none}.msg.assistant.cont{padding-left:38px}
.av.idle .ey-line{animation:av-blink-line 5s infinite}.av.idle .ey-dot{display:inline;opacity:0;animation:av-blink-dot 5s infinite}.av.working .ey-line,.av.done .ey-line{display:none}.av.working .ey-dot{display:inline;opacity:1}.av.working svg{animation:av-tilt 2.4s ease-in-out infinite}.av.working .ear-l{transform-origin:32px 34px;animation:av-twitch 2.4s ease-in-out infinite}.av.done .ey-hap,.av.done .blush{display:inline}.av.done{animation:av-hop .25s ease-out 1}
@keyframes av-blink-line{0%,93%,100%{opacity:1}95%,97%{opacity:0}}@keyframes av-blink-dot{0%,93%,100%{opacity:0}95%,97%{opacity:1}}@keyframes av-tilt{0%,100%{transform:rotate(-8deg)}50%{transform:rotate(8deg)}}@keyframes av-twitch{0%,40%,60%,100%{transform:rotate(0)}48%{transform:rotate(-14deg)}}@keyframes av-hop{0%,100%{transform:translateY(0)}45%{transform:translateY(-4px)}}
@media(prefers-reduced-motion:reduce){.av,.av *{animation:none!important}}
.helpers{margin:0 0 8px;display:grid;gap:4px;font-size:13px;color:var(--muted)}.helper{border:1px solid var(--line);border-radius:12px;background:var(--card)}.helper summary{display:flex;gap:6px;align-items:center;min-height:32px;padding:0 10px;list-style:none;cursor:pointer;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.helper summary::-webkit-details-marker{display:none}.helper summary b{color:var(--text);font-weight:600}.helper p{margin:0;padding:0 10px 8px;white-space:pre-wrap;overflow-wrap:anywhere}.helper .dot{background:#34c759;animation:pulse 1.2s infinite}.helper.stale .dot{background:#ff9f0a;animation:none}
.todo-bar{margin:0 0 8px;border:1px solid var(--line);border-radius:14px;background:var(--card);font-size:14px}
.todo-bar summary{display:flex;gap:8px;align-items:center;min-height:40px;padding:0 12px;list-style:none;cursor:pointer}
.todo-bar summary::-webkit-details-marker{display:none}
.todo-count{flex:none;font-weight:600;font-variant-numeric:tabular-nums}.todo-now{flex:1;min-width:0;color:var(--muted);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.todo-list{margin:0;padding:2px 12px 10px;list-style:none;max-height:38vh;overflow:auto}
.todo-list li{display:flex;gap:8px;padding:5px 0;line-height:1.35}.todo-list li.child{padding-left:22px}
.todo-list li::before{content:"○";flex:none;width:14px;color:var(--muted)}
.todo-list li.active::before{content:"◐";color:var(--text)}.todo-list li.active{font-weight:600}
.todo-list li.done::before{content:"✓"}.todo-list li.done{color:var(--muted);text-decoration:line-through}
.model-chip{flex:none;max-width:46%;padding:5px 10px;border-radius:14px;background:var(--card);border:1px solid var(--line);color:var(--muted);font-size:12.5px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}

.model-sheet [data-model][aria-checked="true"] b::after{content:"  ✓";color:var(--muted)}
.levels{display:flex;flex-wrap:wrap;gap:8px;padding:4px 16px 16px}
.actions .levels button{display:inline-block;width:auto;min-height:36px;padding:6px 12px;border:1px solid var(--line);border-radius:16px;font-size:14px}
.actions .levels button[aria-checked="true"]{background:var(--accent);color:var(--bg);border-color:var(--accent)}
.actions-button{width:32px;height:32px;margin:2px 0;flex:none;border-radius:50%;background:var(--accent);color:var(--bg);font-size:15px}
.actions-shade{position:fixed;inset:0;background:rgba(0,0,0,.18);z-index:20}
.actions{position:fixed;left:12px;right:12px;bottom:calc(84px + var(--keyboard-offset,0px) + env(safe-area-inset-bottom));max-width:720px;margin:auto;background:var(--bg);border-radius:18px;box-shadow:0 10px 40px rgba(0,0,0,.2);overflow:hidden;z-index:21}
.actions.model-sheet{top:calc(env(safe-area-inset-top) + 62px);bottom:auto;max-height:70vh;overflow:auto}
.actions p{margin:0;padding:12px 16px;color:var(--muted);font-size:13px}
.actions button{display:block;width:100%;text-align:left;padding:12px 16px;min-height:56px;border-top:1px solid var(--line);color:var(--text)}
.actions button small{display:block;color:var(--muted);font-size:13px;margin-top:2px}
.actions button:disabled{opacity:.4}
.stop{width:36px;height:36px;border-radius:12px;background:var(--accent);color:var(--bg);font-size:13px;flex:none}.send{width:36px;height:36px;border-radius:12px;background:var(--accent);color:var(--bg);font-size:19px;font-weight:700;flex:none}.send:disabled{opacity:.25}
.shade{position:fixed;inset:0;background:rgba(0,0,0,.18);opacity:0;pointer-events:none;transition:opacity .3s;z-index:2}
.login{position:fixed;inset:0;display:grid;place-items:center;padding:24px;background:var(--bg);z-index:9}.login div{width:min(360px,100%);text-align:center}.login h1{font-size:30px;margin:0 0 6px}.login p{color:var(--muted)}.login input{width:100%;padding:13px 15px;border-radius:14px;border:1px solid var(--line);background:var(--card);margin:12px 0}.login button{width:100%;padding:13px;border-radius:14px;background:var(--accent);color:#fff;font-weight:600}
@media(max-width:760px){.list{position:fixed;left:0;top:0;transform:translateX(-102%)}.open .list{transform:none;box-shadow:20px 0 40px rgba(0,0,0,.12)}.open .shade{opacity:1;pointer-events:auto}}
@media(min-width:761px){#menu{visibility:hidden}}@media(prefers-reduced-motion:reduce){.list,.shade,.activity .chevron{transition:none!important}}.dragging .list,.dragging .shade{transition:none!important}
</style></head><body>
<div class="login" id="login" hidden><div><h1>Pix Remote</h1><p id="loginHelp">Enter the access token shown by <code>/rc</code> on your Mac.</p><input id="token" autocomplete="off" autocapitalize="off" placeholder="Access token"><button id="save">Connect</button></div></div>
<div class="app" id="app"><aside class="list"><h1>Sessions</h1><button type="button" class="row new-session" id="newSession">＋ New session</button><div id="sessions"></div><section class="group" id="memory" aria-label="Memory" hidden><h2>Memory</h2><div id="memoryList"></div></section><button type="button" class="pair-link" id="notify" hidden>Turn on notifications</button><button type="button" class="pair-link" id="copyPair" hidden>Copy pairing link</button></aside><div class="shade" id="shade"></div>
<main class="main"><header><button class="icon" id="menu" aria-label="Sessions">☰</button><div class="title"><b id="title">Pix</b></div><button type="button" class="model-chip" id="modelChip" aria-label="Model" aria-haspopup="dialog" hidden></button><button type="button" class="ctx-ring" id="ctxRing" aria-label="Context" hidden><svg viewBox="0 0 20 20" aria-hidden="true"><circle cx="10" cy="10" r="8" class="track"/><circle cx="10" cy="10" r="8" class="fill" id="ctxFill" pathLength="100" stroke-dasharray="0 100"/></svg></button><span id="connection" class="connection" role="status" aria-label="Connected"></span><button type="button" class="icon" id="filesButton" aria-label="Files" aria-expanded="false">🗂</button></header>
<button type="button" class="to-bottom" id="toBottom" aria-label="Scroll to latest" hidden>↓</button><section class="chat" id="chat"><div class="inner" id="messages"><div class="empty">Run <b>/rc</b> in a Pi session</div></div></section>
<div class="actions-shade" id="modelShade" hidden></div><div class="actions model-sheet" id="modelSheet" role="dialog" aria-label="Model settings" hidden><p>Model</p><div id="modelList"></div><p>Thinking</p><div class="levels" id="levelList"></div></div><div class="actions-shade" id="actionsShade" hidden></div><div class="actions" id="actions" role="menu" aria-label="Quick actions" hidden><p>Quick actions</p><button type="button" role="menuitem" data-action="reload"><b>↻ Reload Pi</b><small>Apply updates. Remote stays on.</small></button><button type="button" role="menuitem" data-action="new"><b>✎ New chat</b><small>Start fresh. Asks first.</small></button><button type="button" role="menuitem" data-action="compact"><b>⇲ Compact</b><small>Shrink a long conversation.</small></button></div>
<form class="composer" id="form"><div class="helpers" id="helpers" hidden></div><details class="todo-bar" id="todoBar" hidden><summary><span class="todo-count" id="todoCount"></span><span class="todo-now" id="todoNow"></span></summary><ol class="todo-list" id="todoList"></ol></details><p class="composer-status" id="composerStatus" role="status" hidden></p><div class="attachment" id="attachment" hidden><span id="attachmentName"></span><button type="button" id="removeImage" aria-label="Remove image">×</button></div><div class="box"><button type="button" class="attach" id="attach" aria-label="Attach image">＋</button><button type="button" class="actions-button" id="actionsButton" aria-label="Quick actions" aria-haspopup="menu" aria-expanded="false">⚡</button><input type="file" id="file" accept="image/png,image/jpeg,image/webp,image/gif" hidden><textarea id="input" rows="1" maxlength="100000" placeholder="Message Pi" enterkeyhint="enter"></textarea><button type="button" class="stop" id="stop" hidden aria-label="Stop Pi">■</button><button class="send" id="send" disabled aria-label="Send">↑</button></div></form></main></div><div class="actions-shade" id="sheetShade" hidden></div><div class="actions model-sheet" id="sheet" role="dialog" aria-labelledby="sheetTitle" hidden><p id="sheetTitle"></p><div class="sheet-list" id="sheetBody"></div></div><div class="memory-view" id="memoryView" role="dialog" aria-labelledby="memoryTitle" hidden><header><button type="button" class="icon" id="closeMemory" aria-label="Close memory">‹</button><div class="title"><b id="memoryTitle"></b></div></header><section class="chat"><div class="inner rich" id="memoryBody"></div></section></div><aside class="files-panel" id="filesPanel" aria-label="Files"><h1>Files</h1><div class="crumbs" id="fileCrumbs"></div><div id="fileList"></div></aside><div class="memory-view file-view" id="fileView" role="dialog" aria-labelledby="fileTitle" hidden><header><button type="button" class="icon" id="closeFile" aria-label="Close file">‹</button><div class="title"><b id="fileTitle"></b></div><button type="button" class="file-action" id="shareFile" hidden>Share</button></header><section class="chat"><div class="inner file-body" id="fileBody"></div></section></div><div class="image-viewer" id="imageViewer" hidden><button type="button" id="closeImage" aria-label="Close image">×</button><img id="fullImage" alt="Conversation image"></div>
<script>
const $=id=>document.getElementById(id);const paired=typeof remoteRelayMode!=="undefined"&&remoteRelayMode;const storageKey=paired?"pixRelayKey":"pixRemoteToken";
let token=localStorage[storageKey]||"",sessions=[],current=null,active=localStorage.pixRemoteSession||"",events,selectedImage=null,sending=false;
const imageCache=new Map(),loadedImages=new Map();
const hash=new URLSearchParams(location.hash.slice(1));if(hash.get(paired?"key":"token")){token=hash.get(paired?"key":"token");localStorage[storageKey]=token;history.replaceState(null,"",location.pathname)}
const api=(path,opts={})=>paired?relayApi(path,opts):fetch(path,{...opts,headers:{"authorization":"Bearer "+token,"content-type":"application/json",...(opts.headers||{})}}).then(async r=>{if(r.status===401){logout();throw new Error("unauthorized")}if(!r.ok)throw new Error((await r.json()).error);return r.json()});
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function pairingKey(value){value=String(value||"").trim();try{const u=new URL(value);value=new URLSearchParams(u.hash.slice(1)).get("key")||""}catch{}return /^[A-Za-z0-9_-]{32,128}$/.test(value)?value:""}
function logout(){localStorage.removeItem(storageKey);token="";$("login").hidden=false;if(paired){const app=matchMedia("(display-mode: standalone)").matches||navigator.standalone;$("loginHelp").innerHTML=app?"This Home Screen app keeps its own storage. In your paired browser, open Sessions and tap <b>Copy pairing link</b>, then paste it here.":"This browser is not paired. Scan the QR from <code>/rc pair</code>, or paste a pairing link.";$("token").placeholder="Pairing link"}events?.close()}
function connect(){if(!token)return logout();$("login").hidden=true;events?.close();events=paired?relayConnect(token):new EventSource("/api/events?token="+encodeURIComponent(token));
events.addEventListener("sessions",e=>{sessions=JSON.parse(e.data);if(pendingNew){const fresh=sessions.find(s=>!pendingNew.known.has(s.id));if(fresh){active=fresh.id;localStorage.pixRemoteSession=fresh.id;pendingNew=null}else if(Date.now()-pendingNew.at>30000)pendingNew=null}if(active&&!sessions.some(s=>s.id===active)&&current?.id===active){missingSince||=Date.now();if(Date.now()-missingSince<30000){renderList();setTimeout(()=>{if(missingSince&&!sessions.some(s=>s.id===active)){missingSince=Date.now()-30000;events.dispatchEvent(new MessageEvent('sessions',{data:JSON.stringify(sessions)}))}},30500);return}}else missingSince=0;if(!sessions.some(s=>s.id===active))active=sessions[0]?.id||"";renderList();if(active&&current?.id!==active)open(active);if(!active){current=null;renderChat()}});
events.addEventListener("session",e=>{const s=JSON.parse(e.data);if(s.id===active){const stick=nearBottom();current=s;renderChat(stick)}});events.addEventListener("sessions",()=>{if(!memoryLoaded){memoryLoaded=true;void loadMemory()}},{once:true});events.onopen=()=>{$("connection").classList.remove("offline");$("connection").setAttribute("aria-label","Connected")};events.onerror=()=>{$("connection").classList.add("offline");$("connection").setAttribute("aria-label","Reconnecting")}}
function sessionGroups(list,now=Date.now()){const day=new Date(now);day.setHours(0,0,0,0);const out=[["Working",[]],["Today",[]],["Earlier",[]]];for(const s of list)out[s.busy||s.waiting?0:s.updatedAt>=day.getTime()?1:2][1].push(s);return out.filter(g=>g[1].length)}
function shortPath(p){return String(p||"").replace(/^\/Users\/[^/]+(?=\/|$)/,"~")}
function renderList(){$("sessions").innerHTML=sessions.length?sessionGroups(sessions).map(([label,items])=>'<section class="group" aria-label="'+label+'"><h2>'+label+'</h2>'+items.map(s=>'<div class="row-wrap"><button class="row '+(s.id===active?"on":"")+'" data-id="'+esc(s.id)+'"><b><span class="dot '+(s.busy?"busy":s.waiting?"wait":"")+'"></span>'+esc(s.name)+'</b>'+(s.named&&s.cwd?'<small>'+esc(shortPath(s.cwd))+'</small>':'')+'</button><button type="button" class="row-more" data-more="'+esc(s.id)+'" aria-label="Close or delete '+esc(s.name)+'">⋯</button></div>').join("")+'</section>').join(""):'<p class="row"><small>No sessions. Run /rc in Pi.</small></p>'}
async function open(id){active=id;filesPath='';localStorage.pixRemoteSession=id;setDrawer(false);renderList();try{current=await api("/api/sessions/"+encodeURIComponent(id));renderChat(true)}catch(e){console.warn(e)}}
function imagesHtml(images,label){return (images||[]).map(image=>{const done=loadedImages.get(current.id+':'+image.id);return '<button type="button" class="image-card'+(done?' loaded':'')+'" data-image="'+esc(image.id)+'" aria-label="View '+esc(label)+'">'+(done?'<img src="'+done.url+'" alt="View '+esc(label)+'" style="aspect-ratio:'+done.w+'/'+done.h+'">':'<span>Loading image…</span>')+'</button>'}).join('')}
function tool(t){return '<details class="tool '+(t.isError?"err":"")+'" data-tool="'+esc(t.id)+'"><summary><b>'+esc(t.name)+'</b>'+(t.label?'<span class="label">'+esc(t.label)+'</span>':'')+'<small>'+(t.output==null?"running…":t.isError?"failed":"done")+'</small></summary>'+(t.input?'<pre>'+esc(t.input)+'</pre>':"")+(t.output?'<pre>'+esc(t.output)+'</pre>':"")+'</details>'}
function background(j,id){return '<details class="background '+(j.state==='failed'?'failed':'')+'" data-background="'+esc(id)+'"><summary><span aria-hidden="true">›</span><b>Job '+esc(j.id)+'</b><span class="status">'+esc(j.state)+'</span><span class="command">'+esc(j.command)+'</span></summary><div class="body">'+(j.output?'<pre>'+esc(j.output)+'</pre>':'<small>No output</small>')+(j.truncated?'<small>Output shortened</small>':'')+(j.fullOutputPath?'<p class="local">Full log on Mac: '+esc(j.fullOutputPath)+'</p>':'')+'</div></details>'}
// One disclosure per consecutive run, following assistant-ui's Tool group pattern without a React runtime.
function activity(tools,id){const failed=tools.filter(t=>t.isError).length,running=tools.filter(t=>t.output==null).length;return '<details class="activity" data-key="g'+esc(id)+'" data-group="'+esc(id)+'"><summary><span class="chevron" aria-hidden="true">›</span><span class="count">'+tools.length+' tool'+(tools.length===1?'':'s')+'</span>'+(running?'<span>· '+running+' running</span>':'')+(failed?'<span class="failure">· '+failed+' failed</span>':'')+(!running&&!failed?'<span>· done</span>':'')+'</summary><div class="activity-list">'+tools.map(tool).join("")+'</div></details>'+tools.filter(t=>t.images?.length).map(t=>'<div class="tool-images">'+imagesHtml(t.images,'tool image')+'</div>').join('')}
// Shiba avatar beside the first bubble of each assistant run; only the newest one shows the session mood.
const shibaFace='<svg viewBox="0 0 100 100" aria-hidden="true"><g class="ear-l"><path d="M25 44 Q21 26 29 21 Q35 19 43 30"/></g><path d="M75 44 Q79 26 71 21 Q65 19 57 30"/><path d="M43 30 Q50 27 57 30"/><path d="M25 44 Q13 58 21 70 Q30 84 50 84 Q70 84 79 70 Q87 58 75 44"/><path d="M29 60 Q35 53 43 57 Q50 61 57 57 Q65 53 71 60 Q72 75 50 78 Q28 75 29 60z" stroke-width="3" opacity=".4"/><circle cx="38" cy="41" r="1.6" opacity=".45"/><circle cx="62" cy="41" r="1.6" opacity=".45"/><ellipse cx="50" cy="62" rx="4" ry="3" fill="#1d1d1f" stroke="#1d1d1f" stroke-width="2"/><path d="M50 65 v3 M44 69 q6 4 6 -1 q0 5 6 1" stroke-width="3"/><g class="ey-line"><path d="M34 51 h8"/><path d="M58 51 h8"/></g><g class="ey-dot" fill="#2f6fa8"><circle cx="38" cy="51" r="3"/><circle cx="62" cy="51" r="3"/></g><g class="ey-hap"><path d="M33 53 q5 -6 10 0"/><path d="M57 53 q5 -6 10 0"/></g><g class="blush" fill="#f2a0a0" stroke="none"><circle cx="30" cy="63" r="4"/><circle cx="70" cy="63" r="4"/></g></svg>';
function avatarHtml(){return '<span class="av idle" aria-hidden="true">'+shibaFace+'</span>'}
let moodSession='',moodBusy=false,doneUntil=0,doneTimer=0;
function avatarMood(busy,doneUntil,now){return busy?'working':now<doneUntil?'done':'idle'}
function trackMood(){const busy=!!current?.busy,same=current?.id===moodSession;const now=Date.now();if(same&&moodBusy&&!busy){doneUntil=now+3000;clearTimeout(doneTimer);doneTimer=setTimeout(()=>applyMood(),3050)}if(!same)doneUntil=0;moodSession=current?.id||'';moodBusy=busy;applyMood()}
function applyMood(){const all=document.querySelectorAll('#messages .av');all.forEach(el=>el.className='av idle');const last=all[all.length-1];if(last)last.className='av '+avatarMood(!!current?.busy,doneUntil,Date.now())}
function helperLine(h){const idle=Math.round((h.idleMs||0)/1000),ago=idle<60?idle+'s':idle<3600?Math.round(idle/60)+'m':Math.round(idle/3600)+'h';return '<details class="helper'+(idle>120?' stale':'')+'" data-helper="'+esc(h.id)+'"><summary><span class="dot"></span><b>'+esc(h.agent)+'</b><span>· '+h.tools+' tool'+(h.tools===1?'':'s')+' · active '+ago+' ago</span></summary>'+(h.task?'<p>'+esc(h.task)+'</p>':'')+'</details>'}
function renderHelpers(){const items=current?.helpers||[],box=$('helpers');box.hidden=!items.length;const open=new Set([...box.querySelectorAll('details[open]')].map(el=>el.dataset.helper));box.innerHTML=items.map(helperLine).join('');for(const el of box.querySelectorAll('details'))if(open.has(el.dataset.helper))el.open=true}
function transcript(messages){let html="",tools=[],groupId="",run=false;const flush=()=>{if(tools.length){html+=activity(tools,groupId);tools=[]}};for(const m of messages){const content=m.html||esc(m.text),rich=m.html?' rich':'';if(m.role==="assistant"){if(m.text||m.images?.length){flush();html+='<div class="msg assistant'+(run?' cont':'')+'" data-key="'+esc(m.id)+'">'+(run?'':avatarHtml())+'<div class="bubble'+rich+'">'+content+imagesHtml(m.images,'assistant image')+'</div></div>'}run=true;if(m.tools?.length){if(!tools.length)groupId=m.id;tools.push(...m.tools)}}else{flush();run=false;html+=m.background?background(m.background,m.id):'<div class="msg '+m.role+'" data-key="'+esc(m.id)+'"><div class="bubble'+rich+'">'+content+imagesHtml(m.images,m.role+' image')+'</div></div>'}}flush();transcriptRun=run;return html}
let transcriptRun=false;
function liveRow(inner){return '<div class="msg assistant'+(transcriptRun?' cont':'')+'">'+(transcriptRun?'':avatarHtml())+inner+'</div>'}
// Follow the bottom while Pi writes, until the reader scrolls up. Only the reader's own scrolling
// stops following; content changes never do. The ↓ button (or scrolling back down) resumes it.
let follow=true,touching=false,userScrollUntil=0;
function atBottom(){const c=$("chat");return c.scrollHeight-c.scrollTop-c.clientHeight<4}
function nearBottom(){return follow}
function toBottom(){const c=$("chat");c.scrollTop=c.scrollHeight}
function setFollow(on){follow=on;$("toBottom").hidden=on}
function userScrolling(){touching=true;userScrollUntil=Date.now()+1200}
function anchor(){const c=$("chat"),top=c.getBoundingClientRect().top;for(const el of $("messages").children){const r=el.getBoundingClientRect();if(r.bottom>top+1&&el.dataset.key)return{key:el.dataset.key,offset:r.top-top}}return null}
function restore(a){if(!a)return;const el=[...$("messages").children].find(e=>e.dataset.key===a.key);if(!el)return;const c=$("chat");c.scrollTop+=el.getBoundingClientRect().top-c.getBoundingClientRect().top-a.offset}
function askCard(q){return '<div class="msg assistant"><div class="ask" data-ask="'+esc(q.id)+'"><p>'+esc(q.question)+'</p>'+q.options.map(o=>'<button type="button" data-answer="'+esc(o.label)+'"><b>'+esc(o.label)+'</b>'+(o.description?'<small>'+esc(o.description)+'</small>':'')+'</button>').join('')+'<p class="hint">Or type your own answer below.</p></div></div>'}
async function answer(value){if(!current?.question)return;try{await api('/api/sessions/'+encodeURIComponent(current.id)+'/action',{method:'POST',body:JSON.stringify({action:'answer',value})});composerStatus('Answered');setTimeout(()=>composerStatus(''),2000)}catch(err){composerStatus(err.message||'Could not answer')}}
function renderChat(stick=true){const keep=stick?null:anchor();const expanded=new Set([...document.querySelectorAll('details.tool[open]')].map(el=>el.dataset.tool));const groups=new Set([...document.querySelectorAll('details.activity[open]')].map(el=>el.dataset.group));const jobs=new Set([...document.querySelectorAll('details.background[open]')].map(el=>el.dataset.background));if(!current){$("title").textContent="Pix";$("messages").innerHTML='<div class="empty">Run <b>/rc</b> in a Pi session</div>';$("send").disabled=true;return}
$("title").textContent=current.name;updateSend();renderModel();
const html=transcript(current.messages)+(current.streaming?liveRow('<div class="bubble'+(current.streamingHtml?' rich':'')+'">'+(current.streamingHtml||esc(current.streaming))+'</div>'):current.question?askCard(current.question):current.busy?liveRow('<div class="bubble typing">Thinking…</div>'):current.waiting?liveRow('<div class="bubble typing">Waiting for '+current.waiting+' background job'+(current.waiting>1?'s':'')+' · Pi resumes when done</div>'):"");
$("messages").innerHTML=html||'<div class="empty">Start the conversation</div>';loadImages();trackMood();for(const el of document.querySelectorAll('details.activity'))if(groups.has(el.dataset.group))el.open=true;for(const el of document.querySelectorAll('details.tool'))if(expanded.has(el.dataset.tool))el.open=true;for(const el of document.querySelectorAll('details.background'))if(jobs.has(el.dataset.background))el.open=true;updateSend();if(stick){setFollow(true);toBottom()}else restore(keep)}
function loadImages(){for(const button of document.querySelectorAll('.image-card:not(.loaded)')){const id=button.dataset.image,key=current.id+':'+id;let pending=imageCache.get(key);if(!pending){pending=api('/api/sessions/'+encodeURIComponent(current.id)+'/media/'+id).then(media=>{if(!['image/png','image/jpeg','image/webp','image/gif'].includes(media.mimeType)||!/^[A-Za-z0-9+/]+={0,2}$/.test(media.data)||media.data.length>1200000)throw Error('Invalid image');return 'data:'+media.mimeType+';base64,'+media.data});imageCache.set(key,pending);if(imageCache.size>24)imageCache.delete(imageCache.keys().next().value)}pending.then(url=>{if(!button.isConnected)return;const img=document.createElement('img');img.onload=()=>{loadedImages.set(key,{url,w:img.naturalWidth||1,h:img.naturalHeight||1});img.style.aspectRatio=img.naturalWidth+'/'+img.naturalHeight;button.classList.add('loaded');if(button.isConnected)button.replaceChildren(img)};img.alt=button.getAttribute('aria-label');img.onerror=()=>{if(button.isConnected)button.textContent='Image unavailable'};img.src=url}).catch(()=>{if(button.isConnected)button.textContent='Image unavailable';imageCache.delete(key)})}}
$("messages").onclick=e=>{const chip=e.target.closest('.file-chip');if(chip){void openFile(chip.dataset.file,chip.dataset.kind);return}const ans=e.target.closest('[data-answer]');if(ans){for(const b of ans.parentElement.querySelectorAll('button'))b.disabled=true;void answer(ans.dataset.answer);return}const card=e.target.closest('.image-card');if(!card)return;const key=current.id+':'+card.dataset.image;imageCache.get(key)?.then(url=>{$('fullImage').src=url;$('imageViewer').hidden=false})};
$('closeImage').onclick=()=>{$('imageViewer').hidden=true;$('fullImage').removeAttribute('src')};$('imageViewer').onclick=e=>{if(e.target===$('imageViewer'))$('closeImage').click()};
$("save").onclick=()=>{const value=paired?pairingKey($("token").value):$("token").value.trim();if(!value){$("loginHelp").textContent="That is not a Pix Remote pairing link.";return}token=value;$("token").value="";localStorage[storageKey]=token;connect()};
// Notifications: iOS allows web push only in a Home Screen app (iOS 16.4+).
const b64u=s=>Uint8Array.from(atob(s.replace(/-/g,"+").replace(/_/g,"/").padEnd(Math.ceil(s.length/4)*4,"=")),c=>c.charCodeAt(0));
async function setupNotify(){const btn=$("notify");if(!("serviceWorker" in navigator))return;
  const reg=await navigator.serviceWorker.register("/sw.js").catch(()=>null);if(!reg)return;btn.hidden=false;
  const standalone=matchMedia("(display-mode: standalone)").matches||navigator.standalone;
  const ready=async()=>{const sub=await reg.pushManager?.getSubscription();if(sub&&Notification.permission==="granted"){try{await api("/api/push",{method:"POST",body:JSON.stringify({subscription:sub.toJSON()})});btn.textContent="Notifications on · send test"}catch{}}};
  if(!("PushManager" in window)){btn.textContent=standalone?"Notifications need iOS 16.4 or later":"Notifications: add Pix to the Home Screen first";btn.disabled=true;return}
  void ready();
  // Tell the Mac when Pix is on screen, so it does not notify this phone while you are reading.
  let endpoint="";const presence=async()=>{endpoint||=(await reg.pushManager.getSubscription())?.endpoint||"";if(!endpoint||!token)return;
    const visible=document.visibilityState==="visible";try{await api("/api/push",{method:"POST",body:JSON.stringify({presence:visible?"visible":"hidden",endpoint})})}catch{}};
  document.addEventListener("visibilitychange",()=>void presence());setInterval(()=>{if(document.visibilityState==="visible")void presence()},10000);void presence();
  btn.onclick=async()=>{try{if(await Notification.requestPermission()!=="granted"){btn.textContent="Notifications blocked in Settings";return}
    const {publicKey}=await api("/api/push");const sub=await reg.pushManager.getSubscription()||await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:b64u(publicKey)});
    await api("/api/push",{method:"POST",body:JSON.stringify({subscription:sub.toJSON(),test:true})});btn.textContent="Notifications on · send test"}catch(e){btn.textContent="Could not turn on: "+(e.message||e)}}}
navigator.serviceWorker?.addEventListener("message",e=>{const id=e.data?.pixOpenSession;if(id)void open(id)});
{const q=new URLSearchParams(location.search).get("session");if(q){active=q;localStorage.pixRemoteSession=q;history.replaceState(null,"","/"+location.hash)}}
setTimeout(()=>void setupNotify(),0);
if(paired){$("copyPair").hidden=false;$("copyPair").onclick=async()=>{try{await navigator.clipboard.writeText(location.origin+"/#key="+token);$("copyPair").textContent="Copied — treat it as a password"}catch{$("copyPair").textContent="Copy failed"}setTimeout(()=>$("copyPair").textContent="Copy pairing link",2500)}}
function setDrawer(open){if(open)setFiles(false);document.body.classList.toggle('open',open);$('menu').setAttribute('aria-expanded',String(open))}
$('menu').setAttribute('aria-expanded','false');$('menu').onclick=()=>setDrawer(!document.body.classList.contains('open'));$('shade').onclick=()=>{setDrawer(false);setFiles(false)};
document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(!$('fileView').hidden)closeFile();else if(document.body.classList.contains('files-open'))setFiles(false);else if(!$('memoryView').hidden)$('closeMemory').click();else if(!$('sheet').hidden)sheet('');else if(!$('imageViewer').hidden)$('closeImage').click();else if(document.body.classList.contains('open')){setDrawer(false);$('menu').focus()}}});
$("sessions").onclick=e=>{if(Date.now()<pressedUntil)return;const m=e.target.closest("[data-more]");if(m)return sessionMenu(m.dataset.more);const b=e.target.closest("[data-id]");if(b)open(b.dataset.id)};
// Long-press a session row for the same Close/Delete menu as its ⋯ button.
let pressTimer,pressedUntil=0;$("sessions").addEventListener('touchstart',e=>{const b=e.target.closest("[data-id]");if(!b)return;pressTimer=setTimeout(()=>{pressedUntil=Date.now()+600;sessionMenu(b.dataset.id)},550)},{passive:true});for(const n of ['touchend','touchmove','touchcancel'])$("sessions").addEventListener(n,()=>clearTimeout(pressTimer),{passive:true});
function sheet(title,html){$('sheetTitle').textContent=title;$('sheetBody').innerHTML=html;$('sheet').hidden=!title;$('sheetShade').hidden=!title}
$('sheetShade').onclick=()=>sheet('');
function sessionMenu(id){const s=sessions.find(x=>x.id===id);if(!s)return;sheet(s.name,'<button type="button" data-close="'+esc(id)+'"><b>Close</b><small>Quit this Pi on the Mac, like /quit. The chat stays saved.</small></button><button type="button" data-delete="'+esc(id)+'"><b>Delete</b><small>Quit and delete its saved session file.</small></button>')}
async function closeSession(id,del){const s=sessions.find(x=>x.id===id);if(!s)return sheet('');if(s.busy){sheet('');composerStatus('Pi is working. Stop it or wait, then try again.');return}
sheet('');if(!confirm(del?'Delete "'+s.name+'"? Pi quits and its saved session file is removed.':'Close "'+s.name+'"? Pi quits on the Mac; the chat stays saved.'))return;
try{await api('/api/sessions/'+encodeURIComponent(id)+'/action',{method:'POST',body:JSON.stringify({action:del?'delete':'close'})});composerStatus(del?'Deleting…':'Closing…');setTimeout(()=>composerStatus(''),4000)}catch(err){composerStatus(err.message||'Could not close')}}
function folderRow(f){return '<button type="button" data-folder="'+esc(f.path)+'"><b>'+esc(f.name)+'</b><small>'+esc(shortPath(f.path))+'</small></button>'}
async function folders(path){try{const r=await api('/api/folders'+(path?'?path='+encodeURIComponent(path):''));
sheet('New session in…',(r.recent?.length?'<p>Recent</p>'+r.recent.map(folderRow).join(''):'')+'<p>'+esc(shortPath(r.path))+'</p><button type="button" data-launch="'+esc(r.path)+'"><b>Start Pi here</b><small>'+esc(shortPath(r.path))+'</small></button>'+(r.parent?'<button type="button" data-browse="'+esc(r.parent)+'"><b>‹ Up</b></button>':'')+r.folders.map(f=>'<button type="button" data-browse="'+esc(f.path)+'"><b>'+esc(f.name)+' ›</b></button>').join(''))}catch(err){setDrawer(false);composerStatus(err.message||'Could not list folders')}}
async function launch(path){sheet('');setDrawer(false);try{pendingNew={at:Date.now(),known:new Set(sessions.map(s=>s.id))};pendingNew.at+=30000;await api('/api/launch',{method:'POST',body:JSON.stringify({path})});composerStatus('Starting Pi in '+shortPath(path)+'…');setTimeout(()=>composerStatus(''),6000)}catch(err){pendingNew=null;composerStatus(err.message||'Could not start Pi')}}
$('newSession').onclick=()=>folders('');
$('sheetBody').onclick=e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.close)closeSession(b.dataset.close,false);else if(b.dataset.delete)closeSession(b.dataset.delete,true);else if(b.dataset.browse)folders(b.dataset.browse);else if(b.dataset.folder||b.dataset.launch)launch(b.dataset.folder||b.dataset.launch)};
async function loadMemory(){try{const items=await api('/api/memory');let last='';$('memoryList').innerHTML=items.map(m=>{const h=m.group!==last?'<small class="row memory-row">'+esc(m.group)+'</small>':'';last=m.group;return h+'<button type="button" class="row memory-row" data-memory="'+esc(m.path)+'"><b>'+esc(m.name)+'</b></button>'}).join('');$('memory').hidden=!items.length}catch{}}
$('memoryList').onclick=async e=>{const b=e.target.closest('[data-memory]');if(!b)return;try{const f=await api('/api/memory/file?path='+encodeURIComponent(b.dataset.memory));$('memoryTitle').textContent=f.path;$('memoryBody').innerHTML=f.html;$('memoryView').hidden=false;setDrawer(false)}catch(err){composerStatus(err.message||'Could not open')}};
$('closeMemory').onclick=()=>{$('memoryView').hidden=true;$('memoryBody').innerHTML=''};
function composerStatus(text){$('composerStatus').textContent=text;$('composerStatus').hidden=!text}
function updateSend(){$('send').disabled=sending||!current||!($('input').value.trim()||selectedImage);const busy=!!current?.busy;const typed=!!($('input').value.trim()||selectedImage);$('stop').hidden=!busy||typed;$('send').hidden=busy&&!typed;$('input').placeholder=busy?'Steer Pi…':'Message Pi';$('send').setAttribute('aria-label',busy?'Send and steer':'Send')}
$('stop').onclick=async()=>{if(!current)return;$('stop').disabled=true;try{await api('/api/sessions/'+encodeURIComponent(current.id)+'/abort',{method:'POST',body:'{}'});composerStatus('')}catch(err){composerStatus(err.message||'Could not stop Pi')}finally{$('stop').disabled=false}};
$('attach').onclick=()=>$('file').click();
// Reader-driven scrolling: a finger or wheel moving up stops following; reaching the bottom resumes it.
{const c=$("chat");let lastTop=0;
c.addEventListener('touchstart',()=>userScrolling(),{passive:true});c.addEventListener('touchend',()=>{touching=false;userScrollUntil=Date.now()+1200},{passive:true});
c.addEventListener('wheel',()=>userScrolling(),{passive:true});
c.addEventListener('scroll',()=>{const reader=touching||Date.now()<userScrollUntil;if(reader){if(c.scrollTop<lastTop-2&&!atBottom())setFollow(false);else if(atBottom())setFollow(true)}lastTop=c.scrollTop},{passive:true});
// Content that grows after rendering (pictures, opened tools) keeps the bottom in view while following.
new ResizeObserver(()=>{if(follow)toBottom()}).observe($("messages"));}
$('toBottom').onclick=()=>{setFollow(true);$("chat").scrollTo({top:$("chat").scrollHeight,behavior:'smooth'})};
let pendingNew=null,missingSince=0,memoryLoaded=false;
const actionNames={reload:'Reload Pi',new:'New chat',compact:'Compact'};
function showActions(open){$('actions').hidden=!open;$('actionsShade').hidden=!open;$('actionsButton').setAttribute('aria-expanded',String(open));for(const b of document.querySelectorAll('#actions [data-action]'))b.disabled=!current||!!current.busy}
$('actionsButton').onclick=()=>showActions($('actions').hidden);$('actionsShade').onclick=()=>showActions(false);
async function runAction(action){showActions(false);if(!current)return false;if(current.busy){composerStatus('Pi is working. Stop it or wait, then try again.');return false}
if(action==='new'&&!confirm('Start a new chat? This conversation stays saved on the Mac.'))return false;
try{if(action==='new')pendingNew={at:Date.now(),known:new Set(sessions.map(s=>s.id))};await api('/api/sessions/'+encodeURIComponent(current.id)+'/action',{method:'POST',body:JSON.stringify({action})});composerStatus(action==='compact'?'Compacting…':action==='reload'?'Reloading Pi…':'Starting a new chat…');setTimeout(()=>composerStatus(''),4000);return true}catch(err){pendingNew=null;composerStatus(err.message||'Could not run '+actionNames[action]);return false}}
function fmtTokens(n){return n>=1000?Math.round(n/1000)+'k':String(n)}
function renderContext(){const c=current?.context,ring=$('ctxRing');ring.hidden=!c;if(!c)return;const pct=c.percent==null?0:Math.min(100,c.percent);
$('ctxFill').setAttribute('stroke-dasharray',pct.toFixed(1)+' 100');ring.classList.toggle('warn',pct>=70&&pct<90);ring.classList.toggle('full',pct>=90);
const label=c.tokens==null?'Context: unknown until the next reply, '+fmtTokens(c.window)+' window':'Context: '+fmtTokens(c.tokens)+' of '+fmtTokens(c.window)+' ('+Math.round(pct)+'%)';ring.setAttribute('aria-label',label);ring.title=label}
$('ctxRing').onclick=()=>composerStatus($('ctxRing').getAttribute('aria-label'));
function renderTodos(){const items=current?.todos||[],bar=$('todoBar');bar.hidden=!items.length||items.every(t=>t.status==='done');if(bar.hidden)return;
const done=items.filter(t=>t.status==='done').length,now=items.find(t=>t.status==='active')||items.find(t=>t.status==='pending');
$('todoCount').textContent=done+'/'+items.length;$('todoNow').textContent=now?now.text:'';
$('todoList').innerHTML=items.map(t=>'<li class="'+esc(t.status)+(t.parentId?' child':'')+'">'+esc(t.text)+'</li>').join('')}
function renderModel(){renderContext();renderHelpers();renderTodos();const m=current?.model;$('modelChip').hidden=!m;if(!m)return;$('modelChip').textContent=m.name+(current.thinking&&current.thinking!=='off'?' · '+current.thinking:'');
$('modelList').innerHTML=(current.models||[]).map(x=>'<button type="button" role="menuitemradio" data-model="'+esc(x.id)+'" aria-checked="'+(x.id===m.id)+'"><b>'+esc(x.name)+'</b><small>'+esc(x.id.split('/')[0])+'</small></button>').join('');
$('levelList').innerHTML=(current.thinkingLevels||[]).map(l=>'<button type="button" role="menuitemradio" data-level="'+esc(l)+'" aria-checked="'+(l===current.thinking)+'">'+esc(l)+'</button>').join('');
for(const b of document.querySelectorAll('#modelSheet button'))b.disabled=!!current.busy}
function showModel(open){$('modelSheet').hidden=!open;$('modelShade').hidden=!open;$('modelChip').setAttribute('aria-expanded',String(open));if(open)renderModel()}
$('modelChip').onclick=()=>showModel($('modelSheet').hidden);$('modelShade').onclick=()=>showModel(false);
$('modelSheet').onclick=async e=>{const b=e.target.closest('[data-model],[data-level]');if(!b||!current)return;if(current.busy){composerStatus('Pi is working. Stop it or wait, then try again.');return}
const body=b.dataset.model?{action:'model',value:b.dataset.model}:{action:'thinking',value:b.dataset.level};
try{await api('/api/sessions/'+encodeURIComponent(current.id)+'/action',{method:'POST',body:JSON.stringify(body)});if(b.dataset.model)showModel(false)}catch(err){composerStatus(err.message||'Could not change the model')}};
$('actions').onclick=e=>{const b=e.target.closest('[data-action]');if(b)runAction(b.dataset.action)};
$('removeImage').onclick=()=>{selectedImage=null;$('file').value='';$('attachment').hidden=true;composerStatus('');updateSend()};
$('file').onchange=async e=>{const file=e.target.files[0];if(!file)return;selectedImage=null;updateSend();composerStatus('Preparing image…');try{if(file.size>12000000)throw Error('Choose an image under 12 MB');const bitmap=await createImageBitmap(file);let width=bitmap.width,height=bitmap.height,scale=Math.min(1,1600/Math.max(width,height));const canvas=document.createElement('canvas');let data='';for(let attempt=0;attempt<6;attempt++){canvas.width=Math.max(1,Math.round(width*scale));canvas.height=Math.max(1,Math.round(height*scale));const context=canvas.getContext('2d');context.fillStyle='#fff';context.fillRect(0,0,canvas.width,canvas.height);context.drawImage(bitmap,0,0,canvas.width,canvas.height);data=canvas.toDataURL('image/jpeg',.76).split(',')[1];if(data.length<=1000000)break;scale*=.7}bitmap.close?.();if(data.length>1000000)throw Error('Image is too large to send');selectedImage={mimeType:'image/jpeg',data};$('attachmentName').textContent=file.name;$('attachment').hidden=false;composerStatus('')}catch(error){composerStatus(error.message||'Could not prepare image')}updateSend()};
$("input").oninput=e=>{e.target.style.height="auto";e.target.style.height=e.target.scrollHeight+"px";updateSend()};
$("input").onkeydown=e=>{if(e.key==="Enter"&&!e.shiftKey&&!e.isComposing&&e.keyCode!==229&&matchMedia("(hover:hover) and (pointer:fine)").matches){e.preventDefault();$("form").requestSubmit()}};
function fitKeyboard(){const vv=window.visualViewport;const focused=document.activeElement===$('input');const offset=focused&&vv?Math.max(0,innerHeight-vv.height-vv.offsetTop):0;document.documentElement.style.setProperty('--keyboard-offset',offset+'px');document.body.classList.toggle('keyboard',focused&&offset>0)}
window.visualViewport?.addEventListener('resize',fitKeyboard);window.visualViewport?.addEventListener('scroll',fitKeyboard);$('input').addEventListener('focus',fitKeyboard);$('input').addEventListener('blur',()=>setTimeout(fitKeyboard,100));
$("form").onsubmit=async e=>{e.preventDefault();const text=$("input").value.trim();const slash=/^\/(reload|new|compact)$/.exec(text);if(slash&&!selectedImage){if(await runAction(slash[1])){$("input").value="";$("input").style.height="auto";updateSend()}return}if(sending||!current||(!text&&!selectedImage))return;const image=selectedImage,sid=current.id;sending=true;setFollow(true);toBottom();updateSend();composerStatus('');try{await api("/api/sessions/"+encodeURIComponent(sid)+"/prompt",{method:"POST",body:JSON.stringify({text,images:image?[image]:[]})});if($("input").value.trim()===text){$("input").value="";$("input").style.height="auto"}if(selectedImage===image){selectedImage=null;$('file').value='';$('attachment').hidden=true}}catch(err){composerStatus(err.message||'Could not send. Try again.')}finally{sending=false;updateSend()}};
let gesture=null;
const point=(touches,id)=>[...touches].find(t=>t.identifier===id);
const panelOf=side=>side==='files'?$('filesPanel'):$('sessions').parentElement;
function clearDrag(){document.body.classList.remove('dragging');$('sessions').parentElement.style.removeProperty('transform');$('filesPanel').style.removeProperty('transform');$('shade').style.removeProperty('opacity');$('shade').style.removeProperty('pointer-events');gesture=null}
// Swipe right opens Sessions from the left; swipe left opens Files from the right, like Messages.
// A wide table or code block keeps a swipe while it can still scroll in that direction.
document.addEventListener('touchstart',e=>{if(e.touches.length!==1)return;const t=e.touches[0],body=document.body.classList,open=body.contains('open')?'sessions':body.contains('files-open')?'files':'',target=e.target;if(target.closest('textarea,input,select,.image-viewer,.actions,.memory-view'))return;if(open==='sessions'?!target.closest('.list,.shade'):open==='files'?!target.closest('.files-panel,.shade'):!target.closest('.chat,header,.composer'))return;
let blockRight=false,blockLeft=false;if(!open){for(let n=target;n&&n!==document.body;n=n.parentElement){if(n.scrollWidth>n.clientWidth+2&&getComputedStyle(n).overflowX!=='visible'){if(n.scrollLeft>0)blockRight=true;if(n.scrollLeft+n.clientWidth<n.scrollWidth-2)blockLeft=true}}}gesture={id:t.identifier,x:t.clientX,y:t.clientY,open,blockRight,blockLeft,tracking:false}},{passive:true});
document.addEventListener('touchmove',e=>{if(!gesture)return;const t=point(e.touches,gesture.id);if(!t||e.touches.length!==1){clearDrag();return}const dx=t.clientX-gesture.x,dy=t.clientY-gesture.y;if(!gesture.tracking){if(Math.abs(dy)>12&&Math.abs(dy)>Math.abs(dx)*.7){clearDrag();return}if(Math.abs(dx)<12||Math.abs(dx)<Math.abs(dy)*1.4)return;const side=gesture.open||(dx>0?'sessions':'files');if(gesture.open==='sessions'&&dx>0||gesture.open==='files'&&dx<0||!gesture.open&&(dx>0?gesture.blockRight:gesture.blockLeft)){gesture=null;return}if(side==='files'&&!current){gesture=null;return}gesture.side=side;gesture.width=panelOf(side).getBoundingClientRect().width;gesture.tracking=true;document.body.classList.add('dragging');if(side==='files'&&!gesture.open&&!filesPath)void showFiles('')}e.preventDefault();const sign=gesture.side==='files'?-1:1,progress=Math.max(0,Math.min(1,((gesture.open?gesture.width:0)+sign*dx)/gesture.width));panelOf(gesture.side).style.transform='translateX('+(sign*(progress-1)*100)+'%)';$('shade').style.opacity=String(progress);$('shade').style.pointerEvents=progress>0?'auto':'none'},{passive:false});
document.addEventListener('touchend',e=>{if(!gesture)return;const t=point(e.changedTouches,gesture.id);if(!t)return;const g=gesture,dx=(t.clientX-g.x)*(g.side==='files'?-1:1),dy=Math.abs(t.clientY-g.y);clearDrag();if(!g.tracking||dy>=60)return;const show=g.open?dx>-g.width*.25:dx>g.width*.25;g.side==='files'?setFiles(show):setDrawer(show)},{passive:true});document.addEventListener('touchcancel',clearDrag,{passive:true});
// Mac files: chips in chat and the right-side Files panel open one viewer. Bytes arrive in 512 KB chunks.
const fileIcons={folder:'📁',pdf:'📕',word:'📝',video:'🎬',audio:'🎵',image:'🖼',sheet:'📊',slides:'📽',markdown:'📄',text:'📄',other:'📎'};
const fmtSize=b=>b<1024?b+' B':b<1048576?Math.round(b/1024)+' KB':(b/1048576).toFixed(b<10485760?1:0)+' MB';
const fileApi=(what,path,extra='')=>api('/api/sessions/'+encodeURIComponent(current.id)+'/'+what+'?path='+encodeURIComponent(path)+extra);
let fileBlob=null,fileUrl='',fileJob=0;
async function fetchFileBlob(path,job,progress){const parts=[];let offset=0,info;for(;;){info=await fileApi('file',path,'&offset='+offset);if(job!==fileJob)throw Error('cancelled');const bin=atob(info.data),bytes=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)bytes[i]=bin.charCodeAt(i);parts.push(bytes);offset+=bytes.length;progress?.(offset,info.size);if(info.done||!bytes.length)break}return {info,blob:new Blob(parts,{type:info.mimeType})}}
function closeFile(){fileJob++;$('fileView').hidden=true;$('fileBody').innerHTML='';$('shareFile').hidden=true;if(fileUrl)URL.revokeObjectURL(fileUrl);fileUrl='';fileBlob=null}
function csvTable(text){const rows=text.split(/\r?\n/).filter(Boolean).slice(0,500).map(line=>{const out=[];let cell='',q=false;for(let i=0;i<line.length;i++){const c=line[i];if(q){if(c=='"'&&line[i+1]=='"'){cell+='"';i++}else if(c=='"')q=false;else cell+=c}else if(c=='"')q=true;else if(c==','){out.push(cell);cell=''}else cell+=c}out.push(cell);return out});return '<div class="table-scroll rich"><table>'+rows.map((r,i)=>'<tr>'+r.map(c=>'<'+(i?'td':'th')+'>'+esc(c)+'</'+(i?'td':'th')+'>').join('')+'</tr>').join('')+'</table></div>'}
async function openFile(path,kind){if(kind==='folder'){await showFiles(path);setFiles(true);return}closeFile();const job=fileJob;const name=path.split('/').pop();$('fileTitle').textContent=name;$('fileView').hidden=false;const body=$('fileBody');body.innerHTML='<p class="file-meta" id="fileProgress">Loading…</p>';
try{if(kind==='word'||kind==='markdown'){const p=fileApi('file/preview',path);const doc=await p;if(job!==fileJob)return;body.innerHTML='<div class="rich doc">'+doc.html+'</div>';$('shareFile').hidden=false;$('shareFile').textContent=kind==='word'?'Download original':'Share';$('shareFile').dataset.path=path;return}
const {info,blob}=await fetchFileBlob(path,job,(n,t)=>{const el=$('fileProgress');if(el)el.textContent='Downloading '+fmtSize(n)+' of '+fmtSize(t)+' ('+Math.round(n*100/Math.max(t,1))+'%)'});fileBlob={blob,name:info.name};fileUrl=URL.createObjectURL(blob);$('shareFile').hidden=false;$('shareFile').textContent='Share';$('shareFile').dataset.path='';
const meta='<p class="file-meta">'+esc(fmtSize(info.size))+'</p>',link='<a class="file-link" href="'+fileUrl+'" target="_blank" rel="noopener" download="'+esc(info.name)+'">Open</a>';
if(info.kind==='image'&&/^image\/(png|jpeg|gif|webp)$/.test(info.mimeType)){$('fileView').hidden=true;$('fullImage').src=fileUrl;$('imageViewer').hidden=false;return}
if(info.kind==='pdf')body.innerHTML='<iframe title="'+esc(info.name)+'" src="'+fileUrl+'"></iframe>'+link;
else if(info.kind==='video')body.innerHTML='<video controls playsinline src="'+fileUrl+'"></video>'+meta;
else if(info.kind==='audio')body.innerHTML=meta+'<audio controls src="'+fileUrl+'"></audio>';
else if(info.kind==='text'||info.mimeType==='text/csv'){const text=await blob.text();body.innerHTML=info.mimeType==='text/csv'?csvTable(text):'<pre><code>'+esc(text)+'</code></pre>'}
else body.innerHTML='<p class="file-meta">'+(fileIcons[info.kind]||'📎')+' '+esc(info.name)+' · '+esc(fmtSize(info.size))+'</p><a class="file-link" href="'+fileUrl+'" download="'+esc(info.name)+'">Download</a>'}
catch(err){if(job===fileJob)body.innerHTML='<p class="file-meta">'+esc(err.message||'Could not open')+'</p>'}}
$('shareFile').onclick=async()=>{try{if($('shareFile').dataset.path){const job=++fileJob;$('shareFile').textContent='Downloading…';const r=await fetchFileBlob($('shareFile').dataset.path,job);fileBlob={blob:r.blob,name:r.info.name};$('shareFile').dataset.path='';$('shareFile').textContent='Share'}const f=new File([fileBlob.blob],fileBlob.name,{type:fileBlob.blob.type});if(navigator.canShare?.({files:[f]})){await navigator.share({files:[f]});return}const a=document.createElement('a');a.href=URL.createObjectURL(fileBlob.blob);a.download=fileBlob.name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),60000)}catch(err){if(err?.name!=='AbortError')composerStatus(err.message||'Could not share')}};
$('closeFile').onclick=closeFile;
let filesPath='';
async function showFiles(path){if(!current)return;try{const r=await fileApi('files',path||'');filesPath=r.path;const rel=r.path===r.home?[]:r.path.slice(r.home.length+1).split('/');let acc=r.home;$('fileCrumbs').innerHTML='<button type="button" data-dir="'+esc(r.home)+'">⌂ Home</button>'+(r.parent?'<button type="button" data-dir="'+esc(r.parent)+'" aria-label="Up">↑</button>':'')+rel.map(p=>{acc+='/'+p;return '<span>/</span><button type="button" data-dir="'+esc(acc)+'">'+esc(p)+'</button>'}).join('');$('fileList').innerHTML=r.entries.map(e=>'<button type="button" class="file-row" data-open="'+esc(e.path)+'" data-kind="'+e.kind+'"><span aria-hidden="true">'+fileIcons[e.kind]+'</span><span class="file-name">'+esc(e.name)+'</span>'+(e.dir?'<small>›</small>':'<small>'+fmtSize(e.size)+'</small>')+'</button>').join('')||'<p class="file-meta">Empty folder</p>'}catch(err){$('fileList').innerHTML='<p class="file-meta">'+esc(err.message||'Folder unavailable')+'</p>'}}
function setFiles(open){if(open)setDrawer(false);document.body.classList.toggle('files-open',open);$('filesButton').setAttribute('aria-expanded',String(open));if(open&&!filesPath&&current)void showFiles('')}
$('filesButton').onclick=()=>setFiles(!document.body.classList.contains('files-open'));
$('fileCrumbs').onclick=e=>{const b=e.target.closest('[data-dir]');if(b)void showFiles(b.dataset.dir)};
$('fileList').onclick=e=>{const b=e.target.closest('[data-open]');if(!b)return;if(b.dataset.kind==='folder')void showFiles(b.dataset.open);else void openFile(b.dataset.open,b.dataset.kind)};
connect();
</script></body></html>`;
