// Static mobile web app served by the remote-control hub. Kept dependency-free so the hub has no build step.

export const remoteIconSvg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 180 180"><rect width="180" height="180" rx="40" fill="#111"/><path d="M58 122V58h38c17 0 28 10 28 25s-11 25-28 25H76v14z" fill="none" stroke="#fff" stroke-width="12" stroke-linejoin="round"/></svg>`;

export const remoteManifest = JSON.stringify({
  name: "Pix Remote",
  short_name: "Pix",
  display: "standalone",
  background_color: "#f5f5f7",
  theme_color: "#f5f5f7",
  start_url: "/",
  icons: [{ src: "/icon.svg", sizes: "any", type: "image/svg+xml", purpose: "any" }],
});

export const remoteAppHtml = String.raw`<!doctype html>
<html lang="en"><head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover,interactive-widget=resizes-content">
<meta name="apple-mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-status-bar-style" content="default">
<meta name="apple-mobile-web-app-title" content="Pix"><meta name="theme-color" content="#f5f5f7">
<link rel="manifest" href="/manifest.webmanifest"><link rel="apple-touch-icon" href="/icon.svg">
<title>Pix Remote</title>
<style>
:root{color-scheme:light dark;--bg:#fff;--panel:rgba(255,255,255,.94);--card:#f7f7f8;--text:#202124;--muted:#777981;--line:rgba(0,0,0,.075);--accent:#26282c;--me:#f1f2f4;--me-text:#202124;--code:#f3f4f5}
@media(prefers-color-scheme:dark){:root{--bg:#17181a;--panel:rgba(23,24,26,.94);--card:#252629;--text:#f3f3f4;--muted:#a0a1a6;--line:rgba(255,255,255,.09);--accent:#ececef;--me:#303136;--me-text:#f3f3f4;--code:#202125}}
[hidden]{display:none!important}*{box-sizing:border-box;-webkit-tap-highlight-color:transparent}html,body{height:100%;margin:0}
body{font:16px/1.45 -apple-system,BlinkMacSystemFont,"SF Pro Text",system-ui,sans-serif;background:var(--bg);color:var(--text);overflow:hidden;-webkit-font-smoothing:antialiased}
button,textarea,input{font:inherit;color:inherit}button{border:0;background:none;cursor:pointer}
.app{position:fixed;inset:0 0 var(--keyboard-offset,0px);display:flex}
.list{width:min(340px,86vw);height:100%;background:var(--panel);backdrop-filter:saturate(180%) blur(24px);-webkit-backdrop-filter:saturate(180%) blur(24px);border-right:1px solid var(--line);padding:calc(env(safe-area-inset-top) + 14px) 12px 12px;overflow:auto;transition:transform .32s cubic-bezier(.2,.8,.2,1);z-index:3}
.list h1{font-size:28px;letter-spacing:-.02em;margin:8px 8px 14px}.row{width:100%;text-align:left;padding:12px;border-radius:14px;display:block}.row.on{background:var(--card);box-shadow:0 1px 2px rgba(0,0,0,.06)}
.row b{display:flex;align-items:center;gap:8px;font-weight:600;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.pair-link{margin:18px 12px;color:var(--muted);font-size:14px;min-height:44px}.group h2{font-size:13px;font-weight:600;color:var(--muted);margin:14px 12px 4px}.group:first-child h2{margin-top:0}.row small{display:block;color:var(--muted);white-space:nowrap;overflow:hidden;text-overflow:ellipsis;margin-top:2px}
.dot{width:7px;height:7px;border-radius:50%;background:#34c759;flex:none}.dot.busy{background:#ff9f0a;animation:pulse 1.2s infinite}@keyframes pulse{50%{opacity:.35}}
.main{flex:1;min-width:0;display:flex;flex-direction:column;height:100%}
header{height:calc(env(safe-area-inset-top) + 54px);padding:env(safe-area-inset-top) 16px 0;display:flex;align-items:center;gap:10px;background:var(--panel);border-bottom:1px solid var(--line);z-index:2}
header .title{flex:1;min-width:0;display:flex;align-items:center;gap:8px}header .title b{display:block;font-size:15px;font-weight:600;letter-spacing:-.01em;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}header .title small{display:none}
.icon{width:44px;height:44px;border-radius:12px;display:grid;place-items:center;color:var(--text);font-size:19px;flex:none}.icon:active{background:var(--card)}
.connection{width:7px;height:7px;border-radius:50%;background:#e0a64c;opacity:0;flex:none}.connection.offline{opacity:1}header .connection{margin-right:13px}
.chat{flex:1;overflow:auto;padding:24px 20px 14px;-webkit-overflow-scrolling:touch}.inner{max-width:720px;margin:auto}
.msg{margin:0 0 22px;display:flex}.msg.user{justify-content:flex-end}.bubble{max-width:90%;white-space:pre-wrap;overflow-wrap:anywhere;min-width:0}
.user .bubble{background:var(--me);color:var(--me-text);padding:10px 15px;border-radius:17px}.assistant .bubble{padding:2px 0;line-height:1.6;max-width:100%}.system .bubble{margin:auto;color:var(--muted);font-size:13px}
.rich{white-space:normal}.rich p{margin:0 0 .8em}.user .rich p{white-space:pre-wrap}.rich p:last-child,.rich>:last-child{margin-bottom:0}.rich h1,.rich h2,.rich h3,.rich h4{font-size:1.12em;line-height:1.3;letter-spacing:-.015em;margin:1.1em 0 .4em;font-weight:650}.rich>:first-child{margin-top:0}.rich ul,.rich ol{padding-left:1.35em;margin:.3em 0 .85em}.rich li{padding-left:.15em;margin:.25em 0}.rich li>p{margin:0}.rich blockquote{margin:.75em 0;padding:.1em 0 .1em .85em;border-left:2px solid var(--line);color:var(--muted)}.rich a{color:#2376ba;text-decoration:underline;text-decoration-color:rgba(35,118,186,.3);text-underline-offset:2px}.rich .local-link{border-bottom:1px dotted var(--muted)}.rich .local-link small{font-size:.73em;margin-left:.35em;color:var(--muted);white-space:nowrap}.rich code{font: .86em/1.45 ui-monospace,SFMono-Regular,Menlo,monospace;background:var(--code);padding:.13em .3em;border-radius:4px;overflow-wrap:anywhere}.rich pre{max-height:none;max-width:100%;margin:.75em 0 1em;white-space:pre;overflow:auto;-webkit-overflow-scrolling:touch;border-radius:9px;padding:12px}.rich pre code{background:none;padding:0;overflow-wrap:normal}.rich hr{border:0;border-top:1px solid var(--line);margin:1em 0}.rich .image-reference{color:var(--muted)}
.activity{margin:0 0 14px;max-width:100%;font-size:13px;color:var(--muted)}.activity>summary{min-height:44px;display:inline-flex;align-items:center;gap:8px;cursor:pointer;list-style:none;padding:0 4px}.activity summary::-webkit-details-marker,.tool summary::-webkit-details-marker{display:none}.activity .chevron{display:inline-block;font-size:15px;transition:transform .2s}.activity[open] .chevron{transform:rotate(90deg)}.activity .count{font-weight:600;color:var(--text)}.activity .failure{color:#d8433e}.activity .activity-list{margin:0 0 0 10px;padding:0 0 0 12px;border-left:1px solid var(--line);max-width:min(620px,90vw)}
.tool{border-radius:10px;overflow:hidden;font-size:13px}.tool summary{padding:5px 8px;min-height:44px;cursor:pointer;list-style:none;display:flex;align-items:center;gap:8px;color:var(--muted)}.tool summary b{color:var(--text);font-weight:500}.tool.err summary b{color:#d8433e}.tool .label{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;min-width:0;flex:1}.tool pre{margin:0 0 8px 8px;border-radius:8px}
.background{margin:0 0 20px;border:1px solid var(--line);background:var(--card);border-radius:12px;max-width:100%;font-size:13px}.background>summary{min-height:44px;padding:9px 12px;display:flex;align-items:center;gap:8px;list-style:none;cursor:pointer}.background summary::-webkit-details-marker{display:none}.background .status{color:var(--muted)}.background.failed .status{color:#d8433e}.background .command{white-space:nowrap;overflow:hidden;text-overflow:ellipsis;min-width:0;flex:1}.background .body{padding:0 12px 12px}.background pre{border-radius:8px;max-height:220px}.background .local{color:var(--muted);font-size:12px;margin:8px 0 0;overflow-wrap:anywhere}
.table-scroll{overflow-x:auto;margin:.6em 0 .9em;-webkit-overflow-scrolling:touch}.rich table{border-collapse:collapse;font-size:14px;line-height:1.4;min-width:100%}.rich th,.rich td{border-bottom:1px solid var(--line);padding:7px 10px;text-align:left;vertical-align:top}.rich th{font-weight:600;white-space:nowrap}.rich tr:last-child td{border-bottom:0}.diagram{margin:.6em 0 .9em}.diagram pre{white-space:pre;overflow-x:auto;overflow-wrap:normal;max-height:none;border-radius:10px;font-size:11.5px;line-height:1.25}.diagram figcaption{color:var(--muted);font-size:13px;margin-bottom:4px}pre{margin:0;padding:10px 11px;background:var(--code);white-space:pre-wrap;overflow-wrap:anywhere;font:12px/1.45 ui-monospace,SFMono-Regular,Menlo,monospace;max-height:280px;overflow:auto}
.image-card{display:block;max-width:min(280px,100%);min-width:120px;min-height:80px;border:1px solid var(--line);border-radius:12px;background:var(--card);overflow:hidden;color:var(--muted);margin:8px 0;text-align:center}.image-card img{display:block;width:100%;max-height:300px;object-fit:contain}.image-card span{display:block;padding:18px}.image-viewer{position:fixed;inset:0;z-index:10;background:rgba(0,0,0,.94);display:flex;align-items:center;justify-content:center;padding:42px 12px env(safe-area-inset-bottom)}.image-viewer img{max-width:100%;max-height:100%;object-fit:contain}.image-viewer button{position:absolute;right:16px;top:calc(env(safe-area-inset-top) + 12px);color:white;width:44px;height:44px;font-size:25px}
.typing{color:var(--muted)}.empty{height:70%;display:grid;place-items:center;text-align:center;color:var(--muted)}
.composer{padding:10px 16px calc(env(safe-area-inset-bottom) + 12px);background:var(--panel)}
.box{max-width:720px;margin:auto;display:flex;align-items:flex-end;gap:8px;background:var(--card);border:1px solid var(--line);border-radius:20px;padding:6px 6px 6px 8px}.attach{width:36px;height:36px;flex:none;font-size:23px;color:var(--muted);border-radius:10px}.attachment{max-width:720px;margin:0 auto 6px;padding:5px 10px;border-radius:10px;background:var(--card);font-size:13px;display:flex;align-items:center;gap:8px}.attachment span{flex:1;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.attachment button{min-width:36px;min-height:36px}.composer-status{max-width:720px;margin:0 auto 5px;color:#b64036;font-size:13px}
textarea{flex:1;border:0;outline:0;resize:none;background:transparent;max-height:140px;padding:6px 0;line-height:1.35}
.stop{width:36px;height:36px;border-radius:12px;background:var(--accent);color:var(--bg);font-size:13px;flex:none}.send{width:36px;height:36px;border-radius:12px;background:var(--accent);color:var(--bg);font-size:19px;font-weight:700;flex:none}.send:disabled{opacity:.25}
.shade{position:fixed;inset:0;background:rgba(0,0,0,.18);opacity:0;pointer-events:none;transition:opacity .3s;z-index:2}
.login{position:fixed;inset:0;display:grid;place-items:center;padding:24px;background:var(--bg);z-index:9}.login div{width:min(360px,100%);text-align:center}.login h1{font-size:30px;margin:0 0 6px}.login p{color:var(--muted)}.login input{width:100%;padding:13px 15px;border-radius:14px;border:1px solid var(--line);background:var(--card);margin:12px 0}.login button{width:100%;padding:13px;border-radius:14px;background:var(--accent);color:#fff;font-weight:600}
@media(max-width:760px){.list{position:fixed;left:0;top:0;transform:translateX(-102%)}.open .list{transform:none;box-shadow:20px 0 40px rgba(0,0,0,.12)}.open .shade{opacity:1;pointer-events:auto}}
@media(min-width:761px){#menu{visibility:hidden}}@media(prefers-reduced-motion:reduce){.list,.shade,.activity .chevron{transition:none!important}}.dragging .list,.dragging .shade{transition:none!important}
</style></head><body>
<div class="login" id="login" hidden><div><h1>Pix Remote</h1><p id="loginHelp">Enter the access token shown by <code>/rc</code> on your Mac.</p><input id="token" autocomplete="off" autocapitalize="off" placeholder="Access token"><button id="save">Connect</button></div></div>
<div class="app" id="app"><aside class="list"><h1>Sessions</h1><div id="sessions"></div><button type="button" class="pair-link" id="copyPair" hidden>Copy pairing link</button></aside><div class="shade" id="shade"></div>
<main class="main"><header><button class="icon" id="menu" aria-label="Sessions">☰</button><div class="title"><b id="title">Pix</b></div><span id="connection" class="connection" role="status" aria-label="Connected"></span></header>
<section class="chat" id="chat"><div class="inner" id="messages"><div class="empty">Run <b>/rc</b> in a Pi session</div></div></section>
<form class="composer" id="form"><p class="composer-status" id="composerStatus" role="status" hidden></p><div class="attachment" id="attachment" hidden><span id="attachmentName"></span><button type="button" id="removeImage" aria-label="Remove image">×</button></div><div class="box"><button type="button" class="attach" id="attach" aria-label="Attach image">＋</button><input type="file" id="file" accept="image/png,image/jpeg,image/webp,image/gif" hidden><textarea id="input" rows="1" maxlength="100000" placeholder="Message Pi" enterkeyhint="enter"></textarea><button type="button" class="stop" id="stop" hidden aria-label="Stop Pi">■</button><button class="send" id="send" disabled aria-label="Send">↑</button></div></form></main></div><div class="image-viewer" id="imageViewer" hidden><button type="button" id="closeImage" aria-label="Close image">×</button><img id="fullImage" alt="Conversation image"></div>
<script>
const $=id=>document.getElementById(id);const paired=typeof remoteRelayMode!=="undefined"&&remoteRelayMode;const storageKey=paired?"pixRelayKey":"pixRemoteToken";
let token=localStorage[storageKey]||"",sessions=[],current=null,active=localStorage.pixRemoteSession||"",events,selectedImage=null,sending=false;
const imageCache=new Map();
const hash=new URLSearchParams(location.hash.slice(1));if(hash.get(paired?"key":"token")){token=hash.get(paired?"key":"token");localStorage[storageKey]=token;history.replaceState(null,"",location.pathname)}
const api=(path,opts={})=>paired?relayApi(path,opts):fetch(path,{...opts,headers:{"authorization":"Bearer "+token,"content-type":"application/json",...(opts.headers||{})}}).then(async r=>{if(r.status===401){logout();throw new Error("unauthorized")}if(!r.ok)throw new Error((await r.json()).error);return r.json()});
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function pairingKey(value){value=String(value||"").trim();try{const u=new URL(value);value=new URLSearchParams(u.hash.slice(1)).get("key")||""}catch{}return /^[A-Za-z0-9_-]{32,128}$/.test(value)?value:""}
function logout(){localStorage.removeItem(storageKey);token="";$("login").hidden=false;if(paired){const app=matchMedia("(display-mode: standalone)").matches||navigator.standalone;$("loginHelp").innerHTML=app?"This Home Screen app keeps its own storage. In your paired browser, open Sessions and tap <b>Copy pairing link</b>, then paste it here.":"This browser is not paired. Scan the QR from <code>/rc pair</code>, or paste a pairing link.";$("token").placeholder="Pairing link"}events?.close()}
function connect(){if(!token)return logout();$("login").hidden=true;events?.close();events=paired?relayConnect(token):new EventSource("/api/events?token="+encodeURIComponent(token));
events.addEventListener("sessions",e=>{sessions=JSON.parse(e.data);if(!sessions.some(s=>s.id===active))active=sessions[0]?.id||"";renderList();if(active&&current?.id!==active)open(active);if(!active){current=null;renderChat()}});
events.addEventListener("session",e=>{const s=JSON.parse(e.data);if(s.id===active){const stick=nearBottom();current=s;renderChat(stick)}});events.onopen=()=>{$("connection").classList.remove("offline");$("connection").setAttribute("aria-label","Connected")};events.onerror=()=>{$("connection").classList.add("offline");$("connection").setAttribute("aria-label","Reconnecting")}}
function sessionGroups(list,now=Date.now()){const day=new Date(now);day.setHours(0,0,0,0);const out=[["Working",[]],["Today",[]],["Earlier",[]]];for(const s of list)out[s.busy?0:s.updatedAt>=day.getTime()?1:2][1].push(s);return out.filter(g=>g[1].length)}
function shortPath(p){return String(p||"").replace(/^\/Users\/[^/]+(?=\/|$)/,"~")}
function renderList(){$("sessions").innerHTML=sessions.length?sessionGroups(sessions).map(([label,items])=>'<section class="group" aria-label="'+label+'"><h2>'+label+'</h2>'+items.map(s=>'<button class="row '+(s.id===active?"on":"")+'" data-id="'+esc(s.id)+'"><b><span class="dot '+(s.busy?"busy":"")+'"></span>'+esc(s.name)+'</b>'+(s.named&&s.cwd?'<small>'+esc(shortPath(s.cwd))+'</small>':'')+'</button>').join("")+'</section>').join(""):'<p class="row"><small>No sessions. Run /rc in Pi.</small></p>'}
async function open(id){active=id;localStorage.pixRemoteSession=id;setDrawer(false);renderList();try{current=await api("/api/sessions/"+encodeURIComponent(id));renderChat(true)}catch(e){console.warn(e)}}
function imagesHtml(images,label){return (images||[]).map(image=>'<button type="button" class="image-card" data-image="'+esc(image.id)+'" aria-label="View '+esc(label)+'"><span>Loading image…</span></button>').join('')}
function tool(t){return '<details class="tool '+(t.isError?"err":"")+'" data-tool="'+esc(t.id)+'"><summary><b>'+esc(t.name)+'</b>'+(t.label?'<span class="label">'+esc(t.label)+'</span>':'')+'<small>'+(t.output==null?"running…":t.isError?"failed":"done")+'</small></summary>'+(t.input?'<pre>'+esc(t.input)+'</pre>':"")+(t.output?'<pre>'+esc(t.output)+'</pre>':"")+'</details>'}
function background(j,id){return '<details class="background '+(j.state==='failed'?'failed':'')+'" data-background="'+esc(id)+'"><summary><span aria-hidden="true">›</span><b>Job '+esc(j.id)+'</b><span class="status">'+esc(j.state)+'</span><span class="command">'+esc(j.command)+'</span></summary><div class="body">'+(j.output?'<pre>'+esc(j.output)+'</pre>':'<small>No output</small>')+(j.truncated?'<small>Output shortened</small>':'')+(j.fullOutputPath?'<p class="local">Full log on Mac: '+esc(j.fullOutputPath)+'</p>':'')+'</div></details>'}
// One disclosure per consecutive run, following assistant-ui's Tool group pattern without a React runtime.
function activity(tools,id){const failed=tools.filter(t=>t.isError).length,running=tools.filter(t=>t.output==null).length;return '<details class="activity" data-group="'+esc(id)+'"><summary><span class="chevron" aria-hidden="true">›</span><span class="count">'+tools.length+' tool'+(tools.length===1?'':'s')+'</span>'+(running?'<span>· '+running+' running</span>':'')+(failed?'<span class="failure">· '+failed+' failed</span>':'')+(!running&&!failed?'<span>· done</span>':'')+'</summary><div class="activity-list">'+tools.map(tool).join("")+'</div></details>'+tools.filter(t=>t.images?.length).map(t=>'<div class="tool-images">'+imagesHtml(t.images,'tool image')+'</div>').join('')}
function transcript(messages){let html="",tools=[],groupId="";const flush=()=>{if(tools.length){html+=activity(tools,groupId);tools=[]}};for(const m of messages){const content=m.html||esc(m.text),rich=m.html?' rich':'';if(m.role==="assistant"){if(m.text||m.images?.length){flush();html+='<div class="msg assistant"><div class="bubble'+rich+'">'+content+imagesHtml(m.images,'assistant image')+'</div></div>'}if(m.tools?.length){if(!tools.length)groupId=m.id;tools.push(...m.tools)}}else{flush();html+=m.background?background(m.background,m.id):'<div class="msg '+m.role+'"><div class="bubble'+rich+'">'+content+imagesHtml(m.images,m.role+' image')+'</div></div>'}}flush();return html}
function nearBottom(){const c=$("chat");return c.scrollHeight-c.scrollTop-c.clientHeight<120}
function renderChat(stick=true){const expanded=new Set([...document.querySelectorAll('details.tool[open]')].map(el=>el.dataset.tool));const groups=new Set([...document.querySelectorAll('details.activity[open]')].map(el=>el.dataset.group));const jobs=new Set([...document.querySelectorAll('details.background[open]')].map(el=>el.dataset.background));if(!current){$("title").textContent="Pix";$("messages").innerHTML='<div class="empty">Run <b>/rc</b> in a Pi session</div>';$("send").disabled=true;return}
$("title").textContent=current.name;updateSend();
const html=transcript(current.messages)+(current.streaming?'<div class="msg assistant"><div class="bubble'+(current.streamingHtml?' rich':'')+'">'+(current.streamingHtml||esc(current.streaming))+'</div></div>':current.busy?'<div class="msg assistant"><div class="bubble typing">Thinking…</div></div>':"");
$("messages").innerHTML=html||'<div class="empty">Start the conversation</div>';loadImages();for(const el of document.querySelectorAll('details.activity'))if(groups.has(el.dataset.group))el.open=true;for(const el of document.querySelectorAll('details.tool'))if(expanded.has(el.dataset.tool))el.open=true;for(const el of document.querySelectorAll('details.background'))if(jobs.has(el.dataset.background))el.open=true;updateSend();if(stick)$("chat").scrollTop=$("chat").scrollHeight}
function loadImages(){for(const button of document.querySelectorAll('.image-card')){const id=button.dataset.image,key=current.id+':'+id;let pending=imageCache.get(key);if(!pending){pending=api('/api/sessions/'+encodeURIComponent(current.id)+'/media/'+id).then(media=>{if(!['image/png','image/jpeg','image/webp','image/gif'].includes(media.mimeType)||!/^[A-Za-z0-9+/]+={0,2}$/.test(media.data)||media.data.length>1200000)throw Error('Invalid image');return 'data:'+media.mimeType+';base64,'+media.data});imageCache.set(key,pending);if(imageCache.size>24)imageCache.delete(imageCache.keys().next().value)}pending.then(url=>{if(!button.isConnected)return;const img=document.createElement('img');img.src=url;img.alt=button.getAttribute('aria-label');img.onerror=()=>{if(button.isConnected)button.textContent='Image unavailable'};button.replaceChildren(img)}).catch(()=>{if(button.isConnected)button.textContent='Image unavailable';imageCache.delete(key)})}}
$("messages").onclick=e=>{const card=e.target.closest('.image-card');if(!card)return;const key=current.id+':'+card.dataset.image;imageCache.get(key)?.then(url=>{$('fullImage').src=url;$('imageViewer').hidden=false})};
$('closeImage').onclick=()=>{$('imageViewer').hidden=true;$('fullImage').removeAttribute('src')};$('imageViewer').onclick=e=>{if(e.target===$('imageViewer'))$('closeImage').click()};
$("save").onclick=()=>{const value=paired?pairingKey($("token").value):$("token").value.trim();if(!value){$("loginHelp").textContent="That is not a Pix Remote pairing link.";return}token=value;$("token").value="";localStorage[storageKey]=token;connect()};
if(paired){$("copyPair").hidden=false;$("copyPair").onclick=async()=>{try{await navigator.clipboard.writeText(location.origin+"/#key="+token);$("copyPair").textContent="Copied — treat it as a password"}catch{$("copyPair").textContent="Copy failed"}setTimeout(()=>$("copyPair").textContent="Copy pairing link",2500)}}
function setDrawer(open){document.body.classList.toggle('open',open);$('menu').setAttribute('aria-expanded',String(open))}
$('menu').setAttribute('aria-expanded','false');$('menu').onclick=()=>setDrawer(!document.body.classList.contains('open'));$('shade').onclick=()=>setDrawer(false);
document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(!$('imageViewer').hidden)$('closeImage').click();else if(document.body.classList.contains('open')){setDrawer(false);$('menu').focus()}}});
$("sessions").onclick=e=>{const b=e.target.closest("[data-id]");if(b)open(b.dataset.id)};
function composerStatus(text){$('composerStatus').textContent=text;$('composerStatus').hidden=!text}
function updateSend(){$('send').disabled=sending||!current||!($('input').value.trim()||selectedImage);const busy=!!current?.busy;const typed=!!($('input').value.trim()||selectedImage);$('stop').hidden=!busy||typed;$('send').hidden=busy&&!typed;$('input').placeholder=busy?'Steer Pi…':'Message Pi';$('send').setAttribute('aria-label',busy?'Send and steer':'Send')}
$('stop').onclick=async()=>{if(!current)return;$('stop').disabled=true;try{await api('/api/sessions/'+encodeURIComponent(current.id)+'/abort',{method:'POST',body:'{}'});composerStatus('')}catch(err){composerStatus(err.message||'Could not stop Pi')}finally{$('stop').disabled=false}};
$('attach').onclick=()=>$('file').click();
$('removeImage').onclick=()=>{selectedImage=null;$('file').value='';$('attachment').hidden=true;composerStatus('');updateSend()};
$('file').onchange=async e=>{const file=e.target.files[0];if(!file)return;selectedImage=null;updateSend();composerStatus('Preparing image…');try{if(file.size>12000000)throw Error('Choose an image under 12 MB');const bitmap=await createImageBitmap(file);let width=bitmap.width,height=bitmap.height,scale=Math.min(1,1600/Math.max(width,height));const canvas=document.createElement('canvas');let data='';for(let attempt=0;attempt<6;attempt++){canvas.width=Math.max(1,Math.round(width*scale));canvas.height=Math.max(1,Math.round(height*scale));const context=canvas.getContext('2d');context.fillStyle='#fff';context.fillRect(0,0,canvas.width,canvas.height);context.drawImage(bitmap,0,0,canvas.width,canvas.height);data=canvas.toDataURL('image/jpeg',.76).split(',')[1];if(data.length<=1000000)break;scale*=.7}bitmap.close?.();if(data.length>1000000)throw Error('Image is too large to send');selectedImage={mimeType:'image/jpeg',data};$('attachmentName').textContent=file.name;$('attachment').hidden=false;composerStatus('')}catch(error){composerStatus(error.message||'Could not prepare image')}updateSend()};
$("input").oninput=e=>{e.target.style.height="auto";e.target.style.height=e.target.scrollHeight+"px";updateSend()};
$("input").onkeydown=e=>{if(e.key==="Enter"&&!e.shiftKey&&!e.isComposing&&e.keyCode!==229&&matchMedia("(hover:hover) and (pointer:fine)").matches){e.preventDefault();$("form").requestSubmit()}};
function fitKeyboard(){const vv=window.visualViewport;const focused=document.activeElement===$('input');const offset=focused&&vv?Math.max(0,innerHeight-vv.height-vv.offsetTop):0;document.documentElement.style.setProperty('--keyboard-offset',offset+'px')}
window.visualViewport?.addEventListener('resize',fitKeyboard);window.visualViewport?.addEventListener('scroll',fitKeyboard);$('input').addEventListener('focus',fitKeyboard);$('input').addEventListener('blur',()=>setTimeout(fitKeyboard,100));
$("form").onsubmit=async e=>{e.preventDefault();const text=$("input").value.trim();if(sending||!current||(!text&&!selectedImage))return;const image=selectedImage,sid=current.id;sending=true;updateSend();composerStatus('');try{await api("/api/sessions/"+encodeURIComponent(sid)+"/prompt",{method:"POST",body:JSON.stringify({text,images:image?[image]:[]})});if($("input").value.trim()===text){$("input").value="";$("input").style.height="auto"}if(selectedImage===image){selectedImage=null;$('file').value='';$('attachment').hidden=true}}catch(err){composerStatus(err.message||'Could not send. Try again.')}finally{sending=false;updateSend()}};
let gesture=null;
const point=(touches,id)=>[...touches].find(t=>t.identifier===id);
function clearDrag(){document.body.classList.remove('dragging');$('sessions').parentElement.style.removeProperty('transform');$('shade').style.removeProperty('opacity');$('shade').style.removeProperty('pointer-events');gesture=null}
document.addEventListener('touchstart',e=>{if(e.touches.length!==1)return;const t=e.touches[0],open=document.body.classList.contains('open'),target=e.target;if(target.closest('textarea,input,button,pre,code,details,.image-viewer'))return;if(open?!target.closest('.list,.shade'):!target.closest('.chat,header')||t.clientX>110)return;gesture={id:t.identifier,x:t.clientX,y:t.clientY,open,width:$('sessions').parentElement.getBoundingClientRect().width,tracking:false,cancelled:false}},{passive:true});
document.addEventListener('touchmove',e=>{if(!gesture)return;const t=point(e.touches,gesture.id);if(!t||e.touches.length!==1){clearDrag();return}const dx=t.clientX-gesture.x,dy=t.clientY-gesture.y;if(!gesture.tracking){if(Math.abs(dy)>12&&Math.abs(dy)>Math.abs(dx)*.7){clearDrag();return}if(Math.abs(dx)<12||Math.abs(dx)<Math.abs(dy)*1.4||gesture.open&&dx>0||!gesture.open&&dx<0)return;gesture.tracking=true;document.body.classList.add('dragging')}e.preventDefault();const progress=Math.max(0,Math.min(1,(gesture.open?gesture.width:0)+dx)/gesture.width);$('sessions').parentElement.style.transform='translateX('+((progress-1)*100)+'%)';$('shade').style.opacity=String(progress);$('shade').style.pointerEvents=progress>0?'auto':'none'},{passive:false});
document.addEventListener('touchend',e=>{if(!gesture)return;const t=point(e.changedTouches,gesture.id);if(!t)return;const dx=t.clientX-gesture.x,dy=Math.abs(t.clientY-gesture.y),open=gesture.open,tracking=gesture.tracking,width=gesture.width;clearDrag();if(tracking&&dy<60)setDrawer(open?dx>-width*.25:dx>width*.25)},{passive:true});document.addEventListener('touchcancel',clearDrag,{passive:true});
connect();
</script></body></html>`;
